/* THORWALLET - i18n translations, part 7: Testimonials / social-proof section.
   On-screen source is English; German (de) restores the original review wording. */
Object.assign(window.__I18N__, {
  "Loved by users": { es:"Adorado por los usuarios", de:"Von Nutzern geliebt", nl:"Geliefd bij gebruikers", uk:"Улюблений користувачами", ru:"Любимый пользователями", fr:"Plébiscité par les utilisateurs", pt:"Amado pelos usuários", zh:"深受用户喜爱", ko:"사용자들이 사랑하는" },
  "Don't just take": { es:"No te quedes solo con", de:"Verlass dich nicht nur auf", nl:"Geloof niet alleen", uk:"Не вірте лише", ru:"Не верьте только", fr:"Ne nous croyez pas", pt:"Não fique só com", zh:"不必只听", ko:"우리 말만" },
  "our word for it.": { es:"nuestra palabra.", de:"unser Wort.", nl:"ons op ons woord.", uk:"нам на слово.", ru:"нам на слово.", fr:"sur parole.", pt:"a nossa palavra.", zh:"我们的一面之词。", ko:"믿지 마세요.", },
  "Unfiltered reviews, straight from the App Store.": { es:"Reseñas sin filtros, directas de la App Store.", de:"Ungefilterte Bewertungen, direkt aus dem App Store.", nl:"Ongefilterde reviews, rechtstreeks uit de App Store.", uk:"Невідфільтровані відгуки, прямо з App Store.", ru:"Неотфильтрованные отзывы, прямо из App Store.", fr:"Des avis non filtrés, directement de l'App Store.", pt:"Avaliações sem filtro, direto da App Store.", zh:"未经修饰的真实评价，直接来自 App Store。", ko:"App Store에서 그대로 가져온 진솔한 리뷰." },
  "on the App Store": { es:"en la App Store", de:"im App Store", nl:"in de App Store", uk:"в App Store", ru:"в App Store", fr:"sur l'App Store", pt:"na App Store", zh:"App Store 评分", ko:"App Store" },
  "ratings": { es:"valoraciones", de:"Bewertungen", nl:"beoordelingen", uk:"оцінок", ru:"оценок", fr:"avis", pt:"avaliações", zh:"个评分", ko:"개 평점" },
  "Read all reviews on the App Store →": { es:"Leer todas las reseñas en la App Store →", de:"Alle Bewertungen im App Store lesen →", nl:"Lees alle reviews in de App Store →", uk:"Читати всі відгуки в App Store →", ru:"Читать все отзывы в App Store →", fr:"Lire tous les avis sur l'App Store →", pt:"Ler todas as avaliações na App Store →", zh:"在 App Store 查看全部评价 →", ko:"App Store에서 모든 리뷰 보기 →" },

  /* Card 1 — SatoshiMaster92 (original English) */
  "Lots of potential": { es:"Mucho potencial", de:"Viel Potenzial", nl:"Veel potentie", uk:"Великий потенціал", ru:"Большой потенциал", fr:"Beaucoup de potentiel", pt:"Muito potencial", zh:"潜力十足", ko:"잠재력이 큽니다" },
  "Everything is working now for me. Thanks to the support team and dev team. There is still some work to do, but this project has potential ✌️": { es:"Ahora todo me funciona. Gracias al equipo de soporte y de desarrollo. Aún queda trabajo por hacer, pero este proyecto tiene potencial ✌️", de:"Bei mir funktioniert jetzt alles. Danke an das Support- und das Dev-Team. Es gibt noch etwas zu tun, aber dieses Projekt hat Potenzial ✌️", nl:"Alles werkt nu voor mij. Dank aan het support- en dev-team. Er is nog wat werk te doen, maar dit project heeft potentie ✌️", uk:"Тепер у мене все працює. Дякую команді підтримки та розробникам. Ще є над чим попрацювати, але цей проєкт має потенціал ✌️", ru:"Теперь у меня всё работает. Спасибо команде поддержки и разработчикам. Ещё есть над чем поработать, но у этого проекта есть потенциал ✌️", fr:"Tout fonctionne maintenant pour moi. Merci à l'équipe support et à l'équipe dev. Il reste du travail, mais ce projet a du potentiel ✌️", pt:"Agora tudo funciona para mim. Obrigado à equipe de suporte e de desenvolvimento. Ainda há trabalho a fazer, mas este projeto tem potencial ✌️", zh:"现在一切都正常了。感谢支持团队和开发团队。虽然还有改进空间，但这个项目很有潜力 ✌️", ko:"이제 모든 것이 잘 작동합니다. 지원팀과 개발팀에 감사합니다. 아직 다듬을 부분은 있지만 이 프로젝트는 잠재력이 있어요 ✌️" },

  /* Card 2 — M_Joyman (original German) */
  "Brilliant solution": { es:"Solución genial", de:"Geniale Lösung", nl:"Geniale oplossing", uk:"Геніальне рішення", ru:"Гениальное решение", fr:"Solution géniale", pt:"Solução genial", zh:"绝妙的方案", ko:"훌륭한 솔루션" },
  "For me, the best solution in the crypto space - especially in combination with the Swiss account.": { es:"Para mí, la mejor solución en el espacio cripto, sobre todo en combinación con la cuenta suiza.", de:"Für mich die beste Lösung im Crypto space – gerade auch in Verbindung mit dem Schweizer Konto.", nl:"Voor mij de beste oplossing in de crypto-wereld, juist ook in combinatie met de Zwitserse rekening.", uk:"Для мене найкраще рішення у крипто-просторі, особливо у поєднанні зі швейцарським рахунком.", ru:"Для меня лучшее решение в крипто-пространстве, особенно в сочетании со швейцарским счётом.", fr:"Pour moi, la meilleure solution dans l'univers crypto, surtout combinée au compte suisse.", pt:"Para mim, a melhor solução no mundo cripto, especialmente em combinação com a conta suíça.", zh:"对我来说，这是加密领域最好的方案——尤其是与瑞士账户结合使用时。", ko:"제게는 크립토 분야에서 최고의 솔루션입니다 — 특히 스위스 계좌와 함께라면 더욱요." },

  /* Card 3 — Alyfast (original German) */
  "Well-made app": { es:"App bien hecha", de:"Gut gemachte App", nl:"Goed gemaakte app", uk:"Якісно зроблений застосунок", ru:"Хорошо сделанное приложение", fr:"Application bien faite", pt:"App bem feito", zh:"做得很好的应用", ko:"잘 만든 앱" },
  "Works flawlessly.": { es:"Funciona perfectamente.", de:"Funktioniert einwandfrei.", nl:"Werkt feilloos.", uk:"Працює бездоганно.", ru:"Работает безупречно.", fr:"Fonctionne parfaitement.", pt:"Funciona perfeitamente.", zh:"运行完美无瑕。", ko:"완벽하게 작동합니다." },

  /* Card 4 — Alucard2689 (original German) */
  "An app with a lot of potential": { es:"Una app con mucho potencial", de:"App mit viel Potenzial", nl:"Een app met veel potentie", uk:"Застосунок із великим потенціалом", ru:"Приложение с большим потенциалом", fr:"Une appli avec beaucoup de potentiel", pt:"Um app com muito potencial", zh:"一款潜力巨大的应用", ko:"잠재력이 큰 앱" },
  "A great app so far, and the dev team actually listens to users' suggestions. I'm excited to see how it all develops in the future.": { es:"Hasta ahora una gran app, y el equipo de desarrollo realmente escucha las sugerencias de los usuarios. Tengo ganas de ver cómo evoluciona todo en el futuro.", de:"Bis jetzt eine tolle App und das Entwicklerteam hört auch auf Vorschläge der Nutzer. Bin gespannt, wie sich das Ganze in Zukunft weiterentwickelt.", nl:"Tot nu toe een geweldige app, en het dev-team luistert echt naar suggesties van gebruikers. Ik ben benieuwd hoe het zich in de toekomst ontwikkelt.", uk:"Поки що чудовий застосунок, і команда розробників справді дослухається до пропозицій користувачів. Цікаво, як усе розвиватиметься далі.", ru:"Пока что отличное приложение, и команда разработчиков действительно прислушивается к предложениям пользователей. Интересно, как всё будет развиваться дальше.", fr:"Une super appli jusqu'ici, et l'équipe de dev écoute vraiment les suggestions des utilisateurs. J'ai hâte de voir comment tout cela évoluera à l'avenir.", pt:"Até agora um ótimo app, e a equipe de desenvolvimento realmente ouve as sugestões dos usuários. Estou curioso para ver como tudo vai evoluir no futuro.", zh:"目前为止是一款很棒的应用，开发团队也真正倾听用户的建议。很期待它未来的发展。", ko:"지금까지 훌륭한 앱이고, 개발팀이 사용자 제안을 실제로 반영합니다. 앞으로 어떻게 발전할지 기대돼요." },
  "Swapped natively": { es:"Intercambiado de forma nativa", de:"Nativ getauscht", nl:"Native geswapt", uk:"Обміняно нативно", ru:"Обменяно нативно", fr:"Échangé nativement", pt:"Trocado nativamente", zh:"原生兑换量", ko:"네이티브 스왑" },
  "Tokens supported": { es:"Tokens admitidos", de:"Unterstützte Token", nl:"Ondersteunde tokens", uk:"Підтримуваних токенів", ru:"Поддерживаемых токенов", fr:"Tokens pris en charge", pt:"Tokens suportados", zh:"支持的代币", ko:"지원 토큰" },
  "Self-custody": { es:"Autocustodia", de:"Selbstverwahrung", nl:"Self-custody", uk:"Самозберігання", ru:"Самостоятельное хранение", fr:"Auto-conservation", pt:"Autocustódia", zh:"自托管", ko:"자가수탁" },
  "Since 2021": { es:"Desde 2021", de:"Seit 2021", nl:"Sinds 2021", uk:"З 2021 року", ru:"С 2021 года", fr:"Depuis 2021", pt:"Desde 2021", zh:"自 2021 年", ko:"2021년부터" },
  "Cumulative cross-chain volume. Variable.": { es:"Volumen cross-chain acumulado. Variable.", de:"Kumuliertes Cross-Chain-Volumen. Variabel.", nl:"Cumulatief cross-chain volume. Variabel.", uk:"Сукупний крос-чейн обсяг. Змінний.", ru:"Совокупный кросс-чейн объём. Переменный.", fr:"Volume cross-chain cumulé. Variable.", pt:"Volume cross-chain acumulado. Variável.", zh:"累计跨链交易量（会变动）。", ko:"누적 크로스체인 거래량. 변동 가능." },
  "Five-star ratings": { es:"Valoraciones de 5 estrellas", de:"Fünf-Sterne-Bewertungen", nl:"Vijfsterrenbeoordelingen", uk:"П’ятизіркові оцінки", ru:"Пятизвёздочные оценки", fr:"Avis cinq étoiles", pt:"Avaliações de 5 estrelas", zh:"五星好评", ko:"별 5개 평점" }
});
