/* THORWALLET - i18n translations, part 4.
   Strings added after the original pass: theme toggle, hero edits, rating,
   store-badge captions, card page (subhero, limits & rewards tables, status,
   tier buttons), final CTAs. Country NAMES and live blog titles stay English. */
Object.assign(window.__I18N__, {
  /* ---- Theme toggle (rendered by theme.js via window.__t) ---- */
  "Light mode": { es:"Modo claro", de:"Heller Modus", nl:"Lichte modus", uk:"Світла тема", ru:"Светлая тема", fr:"Mode clair", pt:"Modo claro", zh:"浅色模式", ko:"라이트 모드" },
  "Dark mode": { es:"Modo oscuro", de:"Dunkler Modus", nl:"Donkere modus", uk:"Темна тема", ru:"Тёмная тема", fr:"Mode sombre", pt:"Modo escuro", zh:"深色模式", ko:"다크 모드" },

  /* ---- Hero (edited copy) ---- */
  "All-in-one mobile DeFi wallet app. Swap BTC, ETH, SOL & more easily.": { es:"App de monedero DeFi móvil todo en uno. Intercambia BTC, ETH, SOL y más con facilidad.", de:"All-in-one mobile DeFi-Wallet-App. Tausche BTC, ETH, SOL & mehr ganz einfach.", nl:"Alles-in-één mobiele DeFi-wallet-app. Wissel eenvoudig BTC, ETH, SOL en meer.", uk:"Універсальний мобільний DeFi-гаманець. Легко обмінюйте BTC, ETH, SOL та інше.", ru:"Универсальное мобильное DeFi-приложение-кошелёк. Легко обменивайте BTC, ETH, SOL и другое.", fr:"Appli de portefeuille DeFi mobile tout-en-un. Échangez BTC, ETH, SOL et plus, facilement.", pt:"App de carteira DeFi móvel tudo-em-um. Troque BTC, ETH, SOL e mais com facilidade.", zh:"一体化移动 DeFi 钱包应用。轻松兑换 BTC、ETH、SOL 等。", ko:"올인원 모바일 DeFi 지갑 앱. BTC, ETH, SOL 등을 손쉽게 스왑하세요." },
  "Secure multi-chain multisig & spend anywhere with your crypto card.": { es:"Multifirma multichain segura y paga en cualquier lugar con tu tarjeta cripto.", de:"Sichere Multichain-Multisig & überall bezahlen mit deiner Krypto-Karte.", nl:"Veilige multichain-multisig en betaal overal met je crypto-kaart.", uk:"Безпечний мультичейн-мультипідпис і оплата будь-де крипто-карткою.", ru:"Безопасный мультичейн-мультиподпись и оплата где угодно крипто-картой.", fr:"Multisig multichaîne sécurisé et payez partout avec votre carte crypto.", pt:"Multisig multichain seguro e pague em qualquer lugar com seu cartão cripto.", zh:"安全的多链多重签名，使用加密卡随处消费。", ko:"안전한 멀티체인 멀티시그, 크립토 카드로 어디서나 결제하세요." },

  /* ---- Rating + store badges ---- */
  "+3000 five-star ratings": { es:"+3000 valoraciones de cinco estrellas", de:"+3000 Fünf-Sterne-Bewertungen", nl:"+3000 vijfsterrenbeoordelingen", uk:"+3000 п'ятизіркових оцінок", ru:"+3000 пятизвёздочных оценок", fr:"+3000 avis cinq étoiles", pt:"+3000 avaliações de cinco estrelas", zh:"超过 3000 个五星好评", ko:"+3000개의 별 5개 평점" },
  "on the App Store & Google Play": { es:"en App Store y Google Play", de:"im App Store & bei Google Play", nl:"in de App Store & Google Play", uk:"в App Store і Google Play", ru:"в App Store и Google Play", fr:"sur l'App Store et Google Play", pt:"na App Store e Google Play", zh:"在 App Store 和 Google Play", ko:"App Store 및 Google Play에서" },
  "Download on the": { es:"Descárgalo en", de:"Laden im", nl:"Download in de", uk:"Завантажте в", ru:"Загрузите в", fr:"Télécharger dans l'", pt:"Baixar na", zh:"下载于", ko:"다운로드:" },
  "Get it on": { es:"Disponible en", de:"Jetzt bei", nl:"Ontdek het op", uk:"Доступно в", ru:"Доступно в", fr:"Disponible sur", pt:"Disponível no", zh:"前往", ko:"다운로드:" },

  /* ---- Home card section link ---- */
  "See all card details & availability": { es:"Ver todos los detalles de la tarjeta y disponibilidad", de:"Alle Kartendetails & Verfügbarkeit ansehen", nl:"Bekijk alle kaartdetails & beschikbaarheid", uk:"Переглянути всі деталі картки та доступність", ru:"Все детали карты и доступность", fr:"Voir tous les détails de la carte et la disponibilité", pt:"Ver todos os detalhes do cartão e disponibilidade", zh:"查看所有卡片详情与可用地区", ko:"카드 상세정보 및 사용 가능 국가 모두 보기" },

  /* ---- Tier card values + buttons ---- */
  "Physical card": { es:"Tarjeta física", de:"Physische Karte", nl:"Fysieke kaart", uk:"Фізична картка", ru:"Физическая карта", fr:"Carte physique", pt:"Cartão físico", zh:"实体卡", ko:"실물 카드" },
  "Can be ordered": { es:"Se puede pedir", de:"Bestellbar", nl:"Kan worden besteld", uk:"Можна замовити", ru:"Можно заказать", fr:"Sur commande", pt:"Pode ser solicitado", zh:"可订购", ko:"주문 가능" },
  "5 minutes": { es:"5 minutos", de:"5 Minuten", nl:"5 minuten", uk:"5 хвилин", ru:"5 минут", fr:"5 minutes", pt:"5 minutos", zh:"5 分钟", ko:"5분" },
  "Join Basic": { es:"Únete a Basic", de:"Basic wählen", nl:"Kies Basic", uk:"Обрати Basic", ru:"Подключить Basic", fr:"Choisir Basic", pt:"Escolher Basic", zh:"加入 Basic", ko:"Basic 가입" },
  "Join Premium": { es:"Únete a Premium", de:"Premium wählen", nl:"Kies Premium", uk:"Обрати Premium", ru:"Подключить Premium", fr:"Choisir Premium", pt:"Escolher Premium", zh:"加入 Premium", ko:"Premium 가입" },
  "Join Swiss Banking": { es:"Únete a Swiss Banking", de:"Swiss Banking wählen", nl:"Kies Swiss Banking", uk:"Обрати Swiss Banking", ru:"Подключить Swiss Banking", fr:"Choisir Swiss Banking", pt:"Escolher Swiss Banking", zh:"加入 Swiss Banking", ko:"Swiss Banking 가입" },
  "Stake $TITN": { es:"Haz staking de $TITN", de:"$TITN staken", nl:"Stake $TITN", uk:"Стейкати $TITN", ru:"Застейкать $TITN", fr:"Staker $TITN", pt:"Fazer stake de $TITN", zh:"质押 $TITN", ko:"$TITN 스테이킹" },

  /* ---- Country availability status ---- */
  "Available": { es:"Disponible", de:"Verfügbar", nl:"Beschikbaar", uk:"Доступно", ru:"Доступно", fr:"Disponible", pt:"Disponível", zh:"可用", ko:"사용 가능" },
  "Not available": { es:"No disponible", de:"Nicht verfügbar", nl:"Niet beschikbaar", uk:"Недоступно", ru:"Недоступно", fr:"Non disponible", pt:"Indisponível", zh:"不可用", ko:"사용 불가" },
  "Search country": { es:"Buscar país", de:"Land suchen", nl:"Land zoeken", uk:"Пошук країни", ru:"Поиск страны", fr:"Rechercher un pays", pt:"Buscar país", zh:"搜索国家/地区", ko:"국가 검색" },

  /* ---- Card page subhero ---- */
  "Spend crypto anywhere Mastercard is accepted, in 175+ countries including the US - all from self-custody. Choose the plan that fits, from a free virtual card to a full Swiss account.": { es:"Paga con cripto en cualquier lugar donde se acepte Mastercard, en más de 175 países incluido EE. UU., todo en autocustodia. Elige el plan que encaje, desde una tarjeta virtual gratuita hasta una cuenta suiza completa.", de:"Bezahle mit Krypto überall, wo Mastercard akzeptiert wird – in über 175 Ländern, auch in den USA, komplett selbstverwahrt. Wähle den passenden Plan, von der kostenlosen virtuellen Karte bis zum vollwertigen Schweizer Konto.", nl:"Geef crypto uit overal waar Mastercard wordt geaccepteerd, in 175+ landen waaronder de VS – volledig self-custody. Kies het plan dat past, van een gratis virtuele kaart tot een volledig Zwitsers account.", uk:"Витрачайте крипту скрізь, де приймають Mastercard, у 175+ країнах, включно зі США — усе на самозберіганні. Оберіть відповідний план: від безкоштовної віртуальної картки до повноцінного швейцарського рахунку.", ru:"Тратьте криптовалюту везде, где принимают Mastercard, в 175+ странах, включая США, — всё на самостоятельном хранении. Выберите подходящий план: от бесплатной виртуальной карты до полноценного швейцарского счёта.", fr:"Dépensez de la crypto partout où Mastercard est accepté, dans plus de 175 pays dont les États-Unis – le tout en auto-conservation. Choisissez le plan qui vous convient, d'une carte virtuelle gratuite à un compte suisse complet.", pt:"Gaste cripto em qualquer lugar que aceite Mastercard, em mais de 175 países incluindo os EUA — tudo em autocustódia. Escolha o plano ideal, de um cartão virtual gratuito a uma conta suíça completa.", zh:"在任何接受 Mastercard 的地方使用加密货币消费，覆盖 175+ 个国家（包括美国），全程自托管。选择适合你的方案，从免费虚拟卡到完整的瑞士账户。", ko:"Mastercard가 사용되는 175개국 이상(미국 포함) 어디서나 크립토로 결제하세요 — 모두 자가수탁 방식입니다. 무료 가상 카드부터 완전한 스위스 계좌까지, 맞는 플랜을 선택하세요." },

  /* ---- Limits & rewards section ---- */
  "Limits & rewards": { es:"Límites y recompensas", de:"Limits & Prämien", nl:"Limieten & beloningen", uk:"Ліміти та винагороди", ru:"Лимиты и вознаграждения", fr:"Limites & récompenses", pt:"Limites e recompensas", zh:"额度与奖励", ko:"한도 & 리워드" },
  "Transparent by design.": { es:"Transparente por diseño.", de:"Transparent von Grund auf.", nl:"Transparant van opzet.", uk:"Прозоро за задумом.", ru:"Прозрачно по замыслу.", fr:"Transparent par conception.", pt:"Transparente por design.", zh:"设计上即透明。", ko:"설계부터 투명하게." },
  "Clear transaction limits and a cashback model that rewards how much you spend - and how much $TITN you stake.": { es:"Límites de transacción claros y un modelo de cashback que premia cuánto gastas y cuánto $TITN tienes en staking.", de:"Klare Transaktionslimits und ein Cashback-Modell, das belohnt, wie viel du ausgibst – und wie viel $TITN du stakst.", nl:"Heldere transactielimieten en een cashbackmodel dat beloont hoeveel je uitgeeft – en hoeveel $TITN je staket.", uk:"Зрозумілі ліміти транзакцій і модель кешбеку, що винагороджує за те, скільки ви витрачаєте — і скільки $TITN стейкаєте.", ru:"Понятные лимиты транзакций и модель кешбэка, которая вознаграждает за то, сколько вы тратите — и сколько $TITN стейкаете.", fr:"Des limites de transaction claires et un modèle de cashback qui récompense ce que vous dépensez – et le montant de $TITN que vous stakez.", pt:"Limites de transação claros e um modelo de cashback que recompensa o quanto você gasta — e quanto $TITN você faz stake.", zh:"清晰的交易额度，以及根据你的消费金额和 $TITN 质押量给予回报的返现模式。", ko:"명확한 거래 한도와, 지출 금액 및 $TITN 스테이킹 양에 따라 보상하는 캐시백 모델." },
  "Transaction limits": { es:"Límites de transacción", de:"Transaktionslimits", nl:"Transactielimieten", uk:"Ліміти транзакцій", ru:"Лимиты транзакций", fr:"Limites de transaction", pt:"Limites de transação", zh:"交易额度", ko:"거래 한도" },
  "Transaction type": { es:"Tipo de transacción", de:"Transaktionstyp", nl:"Transactietype", uk:"Тип транзакції", ru:"Тип транзакции", fr:"Type de transaction", pt:"Tipo de transação", zh:"交易类型", ko:"거래 유형" },
  "POS per transaction": { es:"TPV por transacción", de:"POS pro Transaktion", nl:"POS per transactie", uk:"POS за транзакцію", ru:"POS за транзакцию", fr:"POS par transaction", pt:"POS por transação", zh:"每笔 POS 消费", ko:"POS 1회당" },
  "POS daily limit": { es:"Límite diario TPV", de:"POS-Tageslimit", nl:"POS-daglimiet", uk:"Денний ліміт POS", ru:"Дневной лимит POS", fr:"Limite POS quotidienne", pt:"Limite diário POS", zh:"POS 每日额度", ko:"POS 일일 한도" },
  "POS monthly limit": { es:"Límite mensual TPV", de:"POS-Monatslimit", nl:"POS-maandlimiet", uk:"Місячний ліміт POS", ru:"Месячный лимит POS", fr:"Limite POS mensuelle", pt:"Limite mensal POS", zh:"POS 每月额度", ko:"POS 월 한도" },
  "ATM per transaction": { es:"Cajero por transacción", de:"Geldautomat pro Transaktion", nl:"Geldautomaat per transactie", uk:"Банкомат за транзакцію", ru:"Банкомат за транзакцию", fr:"DAB par transaction", pt:"Caixa eletrônico por transação", zh:"每笔 ATM 取款", ko:"ATM 1회당" },
  "ATM daily limit": { es:"Límite diario cajero", de:"Geldautomat-Tageslimit", nl:"Geldautomaat-daglimiet", uk:"Денний ліміт банкомату", ru:"Дневной лимит банкомата", fr:"Limite DAB quotidienne", pt:"Limite diário do caixa", zh:"ATM 每日额度", ko:"ATM 일일 한도" },
  "ATM monthly limit": { es:"Límite mensual cajero", de:"Geldautomat-Monatslimit", nl:"Geldautomaat-maandlimiet", uk:"Місячний ліміт банкомату", ru:"Месячный лимит банкомата", fr:"Limite DAB mensuelle", pt:"Limite mensal do caixa", zh:"ATM 每月额度", ko:"ATM 월 한도" },
  "Cashback & rewards": { es:"Cashback y recompensas", de:"Cashback & Prämien", nl:"Cashback & beloningen", uk:"Кешбек і винагороди", ru:"Кешбэк и вознаграждения", fr:"Cashback & récompenses", pt:"Cashback e recompensas", zh:"返现与奖励", ko:"캐시백 & 리워드" },
  "Premium users earn cashback based on monthly card spend - the percentage rises as monthly spend increases.": { es:"Los usuarios Premium ganan cashback según su gasto mensual con la tarjeta: el porcentaje aumenta a medida que crece el gasto mensual.", de:"Premium-Nutzer erhalten Cashback basierend auf ihren monatlichen Kartenausgaben – der Prozentsatz steigt mit zunehmenden Ausgaben.", nl:"Premium-gebruikers verdienen cashback op basis van hun maandelijkse kaartuitgaven – het percentage stijgt naarmate de uitgaven toenemen.", uk:"Користувачі Premium отримують кешбек залежно від місячних витрат за карткою — відсоток зростає зі збільшенням витрат.", ru:"Пользователи Premium получают кешбэк в зависимости от месячных трат по карте — процент растёт с увеличением трат.", fr:"Les utilisateurs Premium gagnent du cashback selon leurs dépenses mensuelles par carte – le pourcentage augmente avec les dépenses.", pt:"Usuários Premium ganham cashback com base no gasto mensal no cartão — a porcentagem aumenta conforme o gasto mensal cresce.", zh:"Premium 用户根据每月刷卡消费获得返现，消费越多，返现比例越高。", ko:"Premium 사용자는 월 카드 지출에 따라 캐시백을 받으며, 지출이 늘수록 비율이 높아집니다." },
  "Spend tier": { es:"Nivel de gasto", de:"Ausgaben-Stufe", nl:"Uitgavenniveau", uk:"Рівень витрат", ru:"Уровень трат", fr:"Palier de dépense", pt:"Nível de gasto", zh:"消费等级", ko:"지출 등급" },
  "Monthly spend": { es:"Gasto mensual", de:"Monatliche Ausgaben", nl:"Maandelijkse uitgaven", uk:"Місячні витрати", ru:"Траты в месяц", fr:"Dépense mensuelle", pt:"Gasto mensal", zh:"每月消费", ko:"월 지출" },
  "Cashback": { es:"Cashback", de:"Cashback", nl:"Cashback", uk:"Кешбек", ru:"Кешбэк", fr:"Cashback", pt:"Cashback", zh:"返现", ko:"캐시백" },
  "Tier 1": { es:"Nivel 1", de:"Stufe 1", nl:"Niveau 1", uk:"Рівень 1", ru:"Уровень 1", fr:"Palier 1", pt:"Nível 1", zh:"等级 1", ko:"등급 1" },
  "Tier 2": { es:"Nivel 2", de:"Stufe 2", nl:"Niveau 2", uk:"Рівень 2", ru:"Уровень 2", fr:"Palier 2", pt:"Nível 2", zh:"等级 2", ko:"등급 2" },
  "Tier 3": { es:"Nivel 3", de:"Stufe 3", nl:"Niveau 3", uk:"Рівень 3", ru:"Уровень 3", fr:"Palier 3", pt:"Nível 3", zh:"等级 3", ko:"등급 3" },
  "Tier 4": { es:"Nivel 4", de:"Stufe 4", nl:"Niveau 4", uk:"Рівень 4", ru:"Уровень 4", fr:"Palier 4", pt:"Nível 4", zh:"等级 4", ko:"등급 4" },
  "Monthly cashback caps": { es:"Topes de cashback mensual", de:"Monatliche Cashback-Obergrenzen", nl:"Maandelijkse cashbacklimieten", uk:"Місячні ліміти кешбеку", ru:"Месячные лимиты кешбэка", fr:"Plafonds de cashback mensuels", pt:"Limites de cashback mensal", zh:"每月返现上限", ko:"월 캐시백 한도" },
  "Cashback rewards are subject to a monthly cap based on your $TITN staking tier.": { es:"Las recompensas de cashback están sujetas a un tope mensual según tu nivel de staking de $TITN.", de:"Cashback-Prämien unterliegen einer monatlichen Obergrenze, die von deiner $TITN-Staking-Stufe abhängt.", nl:"Cashbackbeloningen zijn onderworpen aan een maandelijkse limiet op basis van je $TITN-stakingniveau.", uk:"Винагороди кешбеку обмежені місячним лімітом залежно від вашого рівня стейкінгу $TITN.", ru:"Вознаграждения по кешбэку ограничены месячным лимитом в зависимости от вашего уровня стейкинга $TITN.", fr:"Les récompenses de cashback sont soumises à un plafond mensuel selon votre palier de staking $TITN.", pt:"As recompensas de cashback estão sujeitas a um limite mensal com base no seu nível de stake de $TITN.", zh:"返现奖励设有每月上限，具体取决于你的 $TITN 质押等级。", ko:"캐시백 리워드는 $TITN 스테이킹 등급에 따른 월 한도가 적용됩니다." },
  "Stake tier": { es:"Nivel de staking", de:"Staking-Stufe", nl:"Stakingniveau", uk:"Рівень стейкінгу", ru:"Уровень стейкинга", fr:"Palier de staking", pt:"Nível de stake", zh:"质押等级", ko:"스테이킹 등급" },
  "Requirement": { es:"Requisito", de:"Voraussetzung", nl:"Vereiste", uk:"Вимога", ru:"Требование", fr:"Condition", pt:"Requisito", zh:"要求", ko:"요건" },
  "Monthly cashback cap": { es:"Tope de cashback mensual", de:"Monatliche Cashback-Obergrenze", nl:"Maandelijkse cashbacklimiet", uk:"Місячний ліміт кешбеку", ru:"Месячный лимит кешбэка", fr:"Plafond de cashback mensuel", pt:"Limite de cashback mensal", zh:"每月返现上限", ko:"월 캐시백 한도" },
  "No staking requirement": { es:"Sin requisito de staking", de:"Kein Staking erforderlich", nl:"Geen stakingvereiste", uk:"Без вимог до стейкінгу", ru:"Без требований к стейкингу", fr:"Aucun staking requis", pt:"Sem requisito de stake", zh:"无需质押", ko:"스테이킹 불필요" },
  "Community+": { es:"Community+", de:"Community+", nl:"Community+", uk:"Community+", ru:"Community+", fr:"Community+", pt:"Community+", zh:"Community+", ko:"Community+" },

  /* ---- Final CTA (card page) ---- */
  "Card questions, answered.": { es:"Preguntas sobre la tarjeta, respondidas.", de:"Karten-Fragen, beantwortet.", nl:"Kaartvragen, beantwoord.", uk:"Відповіді на запитання про картку.", ru:"Ответы на вопросы о карте.", fr:"Vos questions sur la carte, résolues.", pt:"Perguntas sobre o cartão, respondidas.", zh:"卡片常见问题解答。", ko:"카드 관련 질문 모음." },
  "Get your card.": { es:"Consigue tu tarjeta.", de:"Hol dir deine Karte.", nl:"Haal je kaart.", uk:"Отримайте свою картку.", ru:"Получите свою карту.", fr:"Obtenez votre carte.", pt:"Garanta seu cartão.", zh:"领取你的卡片。", ko:"카드를 받아보세요." },
  "Free in five minutes, straight from self-custody.": { es:"Gratis en cinco minutos, directamente desde la autocustodia.", de:"Kostenlos in fünf Minuten, direkt aus der Selbstverwahrung.", nl:"Gratis in vijf minuten, direct vanuit self-custody.", uk:"Безкоштовно за п'ять хвилин, прямо із самозберігання.", ru:"Бесплатно за пять минут, прямо из самостоятельного хранения.", fr:"Gratuit en cinq minutes, directement depuis l'auto-conservation.", pt:"Grátis em cinco minutos, direto da autocustódia.", zh:"五分钟内免费开通，全程自托管。", ko:"자가수탁에서 바로, 5분 만에 무료로." },

  /* ---- Country list dynamic bits (via countries.js __t) ---- */
  "country": { es:"país", de:"Land", nl:"land", uk:"країна", ru:"страна", fr:"pays", pt:"país", zh:"个国家/地区", ko:"개 국가" },
  "countries": { es:"países", de:"Länder", nl:"landen", uk:"країн", ru:"стран", fr:"pays", pt:"países", zh:"个国家/地区", ko:"개 국가" },
  "No countries match your search.": { es:"Ningún país coincide con tu búsqueda.", de:"Keine Länder entsprechen deiner Suche.", nl:"Geen landen komen overeen met je zoekopdracht.", uk:"Жодна країна не відповідає запиту.", ru:"Нет стран, соответствующих запросу.", fr:"Aucun pays ne correspond à votre recherche.", pt:"Nenhum país corresponde à sua busca.", zh:"没有符合搜索条件的国家/地区。", ko:"검색과 일치하는 국가가 없습니다." }
});
