/* THORWALLET - i18n dictionary, part 8.
   Strings for pages/sections added in the 2026-06 redesign:
   download, swap, compare pages, proof band, fine print, consent.
   Keyed by exact English source string (see i18n.js). */
(function (D) {

/* ---- consent banner ---- */
D["We use one analytics cookie to understand how the site is used - nothing else, and only if you agree."] = { es:"Usamos una sola cookie de analítica para entender cómo se usa el sitio: nada más, y solo si aceptas.", de:"Wir verwenden ein einziges Analyse-Cookie, um zu verstehen, wie die Seite genutzt wird – sonst nichts, und nur mit deiner Zustimmung.", nl:"We gebruiken één analytics-cookie om te begrijpen hoe de site wordt gebruikt - meer niet, en alleen als je akkoord gaat.", uk:"Ми використовуємо лише один аналітичний файл cookie, щоб розуміти, як використовується сайт — нічого більше, і лише за вашою згодою.", ru:"Мы используем один аналитический cookie, чтобы понимать, как используется сайт — ничего больше, и только с вашего согласия.", fr:"Nous utilisons un seul cookie d'analyse pour comprendre l'utilisation du site - rien d'autre, et seulement si vous acceptez.", pt:"Usamos um único cookie de análise para entender como o site é usado - nada mais, e só se você concordar.", zh:"我们仅使用一个分析 Cookie 来了解网站的使用情况——仅此而已，且仅在您同意后启用。", ko:"사이트 사용 현황을 파악하기 위해 분석 쿠키 하나만 사용합니다. 그 외에는 없으며, 동의하실 때만 사용됩니다." };
D["Allow analytics"] = { es:"Permitir analítica", de:"Analyse erlauben", nl:"Analytics toestaan", uk:"Дозволити аналітику", ru:"Разрешить аналитику", fr:"Autoriser l'analyse", pt:"Permitir análise", zh:"允许分析", ko:"분석 허용" };
D["Decline"] = { es:"Rechazar", de:"Ablehnen", nl:"Weigeren", uk:"Відхилити", ru:"Отклонить", fr:"Refuser", pt:"Recusar", zh:"拒绝", ko:"거부" };

/* ---- nav additions ---- */
D["Compare"] = { es:"Comparar", de:"Vergleich", nl:"Vergelijk", uk:"Порівняти", ru:"Сравнить", fr:"Comparer", pt:"Comparar", zh:"对比", ko:"비교" };
D["Compare wallets"] = { es:"Comparar wallets", de:"Wallets vergleichen", nl:"Wallets vergelijken", uk:"Порівняти гаманці", ru:"Сравнить кошельки", fr:"Comparer les wallets", pt:"Comparar carteiras", zh:"钱包对比", ko:"지갑 비교" };
D["vs MetaMask, Trust Wallet & more"] = { es:"vs MetaMask, Trust Wallet y más", de:"vs. MetaMask, Trust Wallet & mehr", nl:"vs MetaMask, Trust Wallet & meer", uk:"проти MetaMask, Trust Wallet та інших", ru:"против MetaMask, Trust Wallet и других", fr:"vs MetaMask, Trust Wallet et plus", pt:"vs MetaMask, Trust Wallet e mais", zh:"对比 MetaMask、Trust Wallet 等", ko:"MetaMask, Trust Wallet 등과 비교" };

/* ---- proof band ---- */
D["Swapped natively - no bridges"] = { es:"Intercambiado de forma nativa, sin bridges", de:"Nativ getauscht – ohne Bridges", nl:"Native geswapt - zonder bridges", uk:"Обміняно нативно — без мостів", ru:"Обменяно нативно — без мостов", fr:"Échangé nativement - sans bridges", pt:"Trocado nativamente - sem bridges", zh:"原生兑换——无跨链桥", ko:"네이티브 스왑 — 브리지 없음" };
D["App Store · 3,000+ five-star ratings"] = { es:"App Store · más de 3.000 valoraciones de 5 estrellas", de:"App Store · über 3.000 Fünf-Sterne-Bewertungen", nl:"App Store · 3.000+ vijfsterrenbeoordelingen", uk:"App Store · понад 3 000 п'ятизіркових оцінок", ru:"App Store · более 3 000 пятизвёздочных оценок", fr:"App Store · plus de 3 000 notes cinq étoiles", pt:"App Store · mais de 3.000 avaliações 5 estrelas", zh:"App Store · 3,000+ 五星好评", ko:"App Store · 5점 리뷰 3,000개 이상" };
D["Tokens across every major chain"] = { es:"Tokens en todas las cadenas principales", de:"Tokens über alle großen Chains", nl:"Tokens op elke grote chain", uk:"Токени на всіх основних мережах", ru:"Токены во всех основных сетях", fr:"Tokens sur toutes les grandes chaînes", pt:"Tokens em todas as principais redes", zh:"覆盖所有主流链的代币", ko:"모든 주요 체인의 토큰" };
D["Winner"] = { es:"Ganador", de:"Gewinner", nl:"Winnaar", uk:"Переможець", ru:"Победитель", fr:"Lauréat", pt:"Vencedor", zh:"冠军", ko:"우승" };
D["Startup World Cup · Pegasus Tech Ventures"] = { es:"Startup World Cup · Pegasus Tech Ventures", de:"Startup World Cup · Pegasus Tech Ventures", nl:"Startup World Cup · Pegasus Tech Ventures", uk:"Startup World Cup · Pegasus Tech Ventures", ru:"Startup World Cup · Pegasus Tech Ventures", fr:"Startup World Cup · Pegasus Tech Ventures", pt:"Startup World Cup · Pegasus Tech Ventures", zh:"创业世界杯 · Pegasus Tech Ventures", ko:"스타트업 월드컵 · Pegasus Tech Ventures" };
D["Top 10"] = { es:"Top 10", de:"Top 10", nl:"Top 10", uk:"Топ-10", ru:"Топ-10", fr:"Top 10", pt:"Top 10", zh:"十强", ko:"톱 10" };
D["Swiss Fintech · Venture Leaders"] = { es:"Fintech suiza · Venture Leaders", de:"Schweizer Fintech · Venture Leaders", nl:"Zwitserse fintech · Venture Leaders", uk:"Швейцарський фінтех · Venture Leaders", ru:"Швейцарский финтех · Venture Leaders", fr:"Fintech suisse · Venture Leaders", pt:"Fintech suíça · Venture Leaders", zh:"瑞士金融科技 · Venture Leaders", ko:"스위스 핀테크 · Venture Leaders" };

/* ---- fine print ---- */
D["The fine print"] = { es:"La letra pequeña", de:"Das Kleingedruckte", nl:"De kleine lettertjes", uk:"Дрібний шрифт", ru:"Мелкий шрифт", fr:"Les petites lignes", pt:"As letras miúdas", zh:"细则", ko:"세부 약관" };
D["Tokenized assets are issued by third parties. Availability varies by jurisdiction. Not investment advice."] = { es:"Los activos tokenizados son emitidos por terceros. La disponibilidad varía según la jurisdicción. No es asesoramiento de inversión.", de:"Tokenisierte Vermögenswerte werden von Dritten ausgegeben. Verfügbarkeit je nach Rechtsraum unterschiedlich. Keine Anlageberatung.", nl:"Getokeniseerde activa worden uitgegeven door derden. Beschikbaarheid verschilt per jurisdictie. Geen beleggingsadvies.", uk:"Токенізовані активи випускаються третіми сторонами. Доступність залежить від юрисдикції. Не є інвестиційною порадою.", ru:"Токенизированные активы выпускаются третьими сторонами. Доступность зависит от юрисдикции. Не является инвестиционной рекомендацией.", fr:"Les actifs tokenisés sont émis par des tiers. Disponibilité variable selon la juridiction. Ceci n'est pas un conseil en investissement.", pt:"Ativos tokenizados são emitidos por terceiros. A disponibilidade varia por jurisdição. Não é aconselhamento de investimento.", zh:"代币化资产由第三方发行。可用性因司法辖区而异。不构成投资建议。", ko:"토큰화 자산은 제3자가 발행합니다. 이용 가능 여부는 관할권에 따라 다릅니다. 투자 조언이 아닙니다." };
D["Yield rates and rebates are variable and not guaranteed."] = { es:"Los rendimientos y reembolsos son variables y no están garantizados.", de:"Renditen und Rückvergütungen sind variabel und nicht garantiert.", nl:"Rendementen en rebates zijn variabel en niet gegarandeerd.", uk:"Ставки доходності та відшкодування змінні й не гарантуються.", ru:"Ставки доходности и возвраты переменны и не гарантируются.", fr:"Les rendements et remises sont variables et non garantis.", pt:"Os rendimentos e rebates são variáveis e não garantidos.", zh:"收益率与返还均为浮动，且不作保证。", ko:"수익률과 리베이트는 변동되며 보장되지 않습니다." };
D["$TITN is a utility token, not an investment. Its value may fluctuate and could fall to zero. See full"] = { es:"$TITN es un token de utilidad, no una inversión. Su valor puede fluctuar y caer a cero. Consulta los", de:"$TITN ist ein Utility-Token, keine Geldanlage. Sein Wert kann schwanken und auf null fallen. Siehe vollständige", nl:"$TITN is een utility-token, geen belegging. De waarde kan schommelen en tot nul dalen. Zie de volledige", uk:"$TITN — це утилітарний токен, а не інвестиція. Його вартість може коливатися й впасти до нуля. Див. повні", ru:"$TITN — это утилитарный токен, а не инвестиция. Его стоимость может колебаться и упасть до нуля. См. полные", fr:"$TITN est un jeton utilitaire, pas un investissement. Sa valeur peut fluctuer et tomber à zéro. Voir les", pt:"$TITN é um token utilitário, não um investimento. Seu valor pode flutuar e cair a zero. Veja os", zh:"$TITN 是实用型代币，并非投资品。其价值可能波动甚至归零。请参阅完整的", ko:"$TITN은 투자 상품이 아닌 유틸리티 토큰입니다. 가치가 변동될 수 있으며 0이 될 수도 있습니다. 전체" };
D["terms & risks"] = { es:"términos y riesgos", de:"Bedingungen & Risiken", nl:"voorwaarden & risico's", uk:"умови та ризики", ru:"условия и риски", fr:"conditions et risques", pt:"termos e riscos", zh:"条款与风险", ko:"약관 및 위험 안내" };
D["full terms & risks"] = { es:"términos y riesgos completos", de:"vollständigen Bedingungen & Risiken", nl:"volledige voorwaarden & risico's", uk:"повні умови та ризики", ru:"полные условия и риски", fr:"conditions et risques complets", pt:"termos e riscos completos", zh:"完整条款与风险", ko:"전체 약관 및 위험 안내" };
D["before staking."] = { es:"antes de hacer staking.", de:"vor dem Staking.", nl:"vóór het staken.", uk:"перед стейкінгом.", ru:"перед стейкингом.", fr:"avant de staker.", pt:"antes de fazer staking.", zh:"质押前请阅读。", ko:"스테이킹 전에 확인하세요." };
D["Cashback rates and monthly caps depend on plan, monthly card spend and $TITN staking tier, and may change."] = { es:"Las tasas de cashback y los límites mensuales dependen del plan, del gasto mensual con tarjeta y del nivel de staking de $TITN, y pueden cambiar.", de:"Cashback-Sätze und Monatslimits hängen von Plan, monatlichem Kartenumsatz und $TITN-Staking-Stufe ab und können sich ändern.", nl:"Cashbackpercentages en maandlimieten hangen af van plan, maandelijkse kaartuitgaven en $TITN-stakingniveau en kunnen wijzigen.", uk:"Ставки кешбеку та місячні ліміти залежать від плану, місячних витрат карткою та рівня стейкінгу $TITN і можуть змінюватися.", ru:"Ставки кешбэка и месячные лимиты зависят от плана, месячных трат по карте и уровня стейкинга $TITN и могут меняться.", fr:"Les taux de cashback et plafonds mensuels dépendent du plan, des dépenses mensuelles par carte et du niveau de staking $TITN, et peuvent évoluer.", pt:"As taxas de cashback e os limites mensais dependem do plano, do gasto mensal no cartão e do nível de staking de $TITN, e podem mudar.", zh:"返现比例与每月上限取决于套餐、每月刷卡消费及 $TITN 质押等级，并可能调整。", ko:"캐시백 비율과 월 한도는 플랜, 월 카드 사용액, $TITN 스테이킹 등급에 따라 달라지며 변경될 수 있습니다." };
D["Mastercard is a registered trademark of Mastercard International."] = { es:"Mastercard es una marca registrada de Mastercard International.", de:"Mastercard ist eine eingetragene Marke von Mastercard International.", nl:"Mastercard is een geregistreerd handelsmerk van Mastercard International.", uk:"Mastercard — зареєстрована торгова марка Mastercard International.", ru:"Mastercard — зарегистрированная торговая марка Mastercard International.", fr:"Mastercard est une marque déposée de Mastercard International.", pt:"Mastercard é uma marca registrada da Mastercard International.", zh:"Mastercard 是 Mastercard International 的注册商标。", ko:"Mastercard는 Mastercard International의 등록 상표입니다." };
D["Swap fees, rebates and volume discounts are variable and may change."] = { es:"Las comisiones de swap, reembolsos y descuentos por volumen son variables y pueden cambiar.", de:"Swap-Gebühren, Rückvergütungen und Volumenrabatte sind variabel und können sich ändern.", nl:"Swapkosten, rebates en volumekortingen zijn variabel en kunnen wijzigen.", uk:"Комісії за обмін, відшкодування та знижки за обсяг змінні й можуть змінюватися.", ru:"Комиссии за обмен, возвраты и скидки за объём переменны и могут меняться.", fr:"Les frais de swap, remises et rabais de volume sont variables et peuvent évoluer.", pt:"As taxas de swap, rebates e descontos por volume são variáveis e podem mudar.", zh:"兑换费用、返还及交易量折扣均为浮动，可能调整。", ko:"스왑 수수료, 리베이트, 거래량 할인은 변동되며 변경될 수 있습니다." };
D["$TITN is a utility token, not an investment. Its value may fluctuate and could fall to zero. Nothing here is financial advice. Read the"] = { es:"$TITN es un token de utilidad, no una inversión. Su valor puede fluctuar y caer a cero. Nada de esto es asesoramiento financiero. Lee los", de:"$TITN ist ein Utility-Token, keine Geldanlage. Sein Wert kann schwanken und auf null fallen. Nichts hiervon ist Finanzberatung. Lies die", nl:"$TITN is een utility-token, geen belegging. De waarde kan schommelen en tot nul dalen. Niets hiervan is financieel advies. Lees de", uk:"$TITN — це утилітарний токен, а не інвестиція. Його вартість може коливатися й впасти до нуля. Це не фінансова порада. Прочитайте", ru:"$TITN — это утилитарный токен, а не инвестиция. Его стоимость может колебаться и упасть до нуля. Это не финансовая рекомендация. Прочитайте", fr:"$TITN est un jeton utilitaire, pas un investissement. Sa valeur peut fluctuer et tomber à zéro. Rien ici n'est un conseil financier. Lisez les", pt:"$TITN é um token utilitário, não um investimento. Seu valor pode flutuar e cair a zero. Nada aqui é aconselhamento financeiro. Leia os", zh:"$TITN 是实用型代币，并非投资品。其价值可能波动甚至归零。本页内容不构成财务建议。质押前请阅读", ko:"$TITN은 투자 상품이 아닌 유틸리티 토큰입니다. 가치가 변동될 수 있으며 0이 될 수도 있습니다. 본 내용은 금융 조언이 아닙니다. 스테이킹 전" };
D["Swap fees, rebates and volume discounts are variable and may change. $TITN is a utility token, not an investment; its value may fluctuate and could fall to zero."] = { es:"Las comisiones de swap, reembolsos y descuentos por volumen son variables y pueden cambiar. $TITN es un token de utilidad, no una inversión; su valor puede fluctuar y caer a cero.", de:"Swap-Gebühren, Rückvergütungen und Volumenrabatte sind variabel und können sich ändern. $TITN ist ein Utility-Token, keine Geldanlage; sein Wert kann schwanken und auf null fallen.", nl:"Swapkosten, rebates en volumekortingen zijn variabel en kunnen wijzigen. $TITN is een utility-token, geen belegging; de waarde kan schommelen en tot nul dalen.", uk:"Комісії за обмін, відшкодування та знижки за обсяг змінні й можуть змінюватися. $TITN — утилітарний токен, а не інвестиція; його вартість може коливатися й впасти до нуля.", ru:"Комиссии за обмен, возвраты и скидки за объём переменны и могут меняться. $TITN — утилитарный токен, а не инвестиция; его стоимость может колебаться и упасть до нуля.", fr:"Les frais de swap, remises et rabais de volume sont variables et peuvent évoluer. $TITN est un jeton utilitaire, pas un investissement ; sa valeur peut fluctuer et tomber à zéro.", pt:"As taxas de swap, rebates e descontos por volume são variáveis e podem mudar. $TITN é um token utilitário, não um investimento; seu valor pode flutuar e cair a zero.", zh:"兑换费用、返还及交易量折扣均为浮动，可能调整。$TITN 是实用型代币，并非投资品；其价值可能波动甚至归零。", ko:"스왑 수수료, 리베이트, 거래량 할인은 변동되며 변경될 수 있습니다. $TITN은 투자 상품이 아닌 유틸리티 토큰이며, 가치가 변동되어 0이 될 수도 있습니다." };
D["Gasless execution is available on supported routes only. Network conditions can affect settlement times."] = { es:"La ejecución sin gas solo está disponible en rutas compatibles. Las condiciones de la red pueden afectar los tiempos de liquidación.", de:"Gaslose Ausführung ist nur auf unterstützten Routen verfügbar. Netzwerkbedingungen können die Abwicklungszeiten beeinflussen.", nl:"Gasloze uitvoering is alleen beschikbaar op ondersteunde routes. Netwerkomstandigheden kunnen de afwikkeltijd beïnvloeden.", uk:"Виконання без газу доступне лише на підтримуваних маршрутах. Стан мережі може впливати на час розрахунків.", ru:"Исполнение без газа доступно только на поддерживаемых маршрутах. Состояние сети может влиять на время расчётов.", fr:"L'exécution sans gas n'est disponible que sur les routes prises en charge. L'état du réseau peut affecter les délais de règlement.", pt:"A execução sem gás está disponível apenas em rotas compatíveis. As condições da rede podem afetar os tempos de liquidação.", zh:"免 Gas 执行仅适用于受支持的路径。网络状况可能影响结算时间。", ko:"가스리스 실행은 지원되는 경로에서만 가능합니다. 네트워크 상태에 따라 정산 시간이 달라질 수 있습니다." };

/* ---- download page ---- */
D["One wallet."] = { es:"Una wallet.", de:"Eine Wallet.", nl:"Eén wallet.", uk:"Один гаманець.", ru:"Один кошелёк.", fr:"Un seul wallet.", pt:"Uma carteira.", zh:"一个钱包。", ko:"하나의 지갑." };
D["Every device."] = { es:"Todos tus dispositivos.", de:"Jedes Gerät.", nl:"Elk apparaat.", uk:"Кожен пристрій.", ru:"Каждое устройство.", fr:"Tous vos appareils.", pt:"Todos os dispositivos.", zh:"覆盖每台设备。", ko:"모든 기기에서." };
D["Self-custody swaps, multisig vaults and a Swiss account with a global Mastercard - on iOS, Android and the web. Your keys never leave your device."] = { es:"Swaps en auto-custodia, vaults multifirma y una cuenta suiza con Mastercard global, en iOS, Android y la web. Tus claves nunca salen de tu dispositivo.", de:"Selbstverwahrte Swaps, Multisig-Vaults und ein Schweizer Konto mit globaler Mastercard – auf iOS, Android und im Web. Deine Schlüssel verlassen nie dein Gerät.", nl:"Swaps in zelfbeheer, multisig-vaults en een Zwitserse rekening met wereldwijde Mastercard - op iOS, Android en web. Je sleutels verlaten nooit je apparaat.", uk:"Обміни в самозберіганні, мультипідписні сховища та швейцарський рахунок із глобальною Mastercard — на iOS, Android та в браузері. Ваші ключі ніколи не залишають пристрій.", ru:"Обмены с самостоятельным хранением, мультиподписные хранилища и швейцарский счёт с глобальной Mastercard — на iOS, Android и в вебе. Ваши ключи никогда не покидают устройство.", fr:"Swaps en auto-conservation, coffres multisig et compte suisse avec Mastercard mondiale - sur iOS, Android et le web. Vos clés ne quittent jamais votre appareil.", pt:"Swaps em autocustódia, cofres multisig e uma conta suíça com Mastercard global - no iOS, Android e na web. Suas chaves nunca saem do seu dispositivo.", zh:"自托管兑换、多签金库，以及配全球 Mastercard 的瑞士账户——支持 iOS、Android 和网页端。您的私钥永不离开设备。", ko:"셀프 커스터디 스왑, 멀티시그 볼트, 글로벌 Mastercard가 포함된 스위스 계좌 — iOS, Android, 웹에서. 키는 절대 기기를 떠나지 않습니다." };
D["Get the app in seconds."] = { es:"Consigue la app en segundos.", de:"Hol dir die App in Sekunden.", nl:"Download de app in seconden.", uk:"Отримайте застосунок за секунди.", ru:"Получите приложение за секунды.", fr:"Obtenez l'app en quelques secondes.", pt:"Baixe o app em segundos.", zh:"几秒钟即可获取应用。", ko:"몇 초 만에 앱 받기." };
D["Point your phone camera at the code and you'll land in the right store automatically - or pick your platform below."] = { es:"Apunta la cámara de tu móvil al código y llegarás a la tienda correcta automáticamente, o elige tu plataforma abajo.", de:"Richte deine Handykamera auf den Code und du landest automatisch im richtigen Store – oder wähle unten deine Plattform.", nl:"Richt je telefooncamera op de code en je komt automatisch in de juiste store - of kies hieronder je platform.", uk:"Наведіть камеру телефона на код — і автоматично потрапите в потрібний магазин, або оберіть платформу нижче.", ru:"Наведите камеру телефона на код — и автоматически попадёте в нужный магазин, или выберите платформу ниже.", fr:"Pointez l'appareil photo de votre téléphone sur le code et vous arriverez automatiquement sur la bonne boutique - ou choisissez votre plateforme ci-dessous.", pt:"Aponte a câmera do celular para o código e você chegará à loja certa automaticamente - ou escolha sua plataforma abaixo.", zh:"用手机相机对准二维码即可自动跳转到对应商店，或在下方选择您的平台。", ko:"휴대폰 카메라로 코드를 비추면 자동으로 맞는 스토어로 이동합니다. 아래에서 플랫폼을 직접 선택할 수도 있습니다." };
D["Scan with your phone camera"] = { es:"Escanea con la cámara del móvil", de:"Mit der Handykamera scannen", nl:"Scan met je telefooncamera", uk:"Скануйте камерою телефона", ru:"Сканируйте камерой телефона", fr:"Scannez avec votre téléphone", pt:"Escaneie com a câmera do celular", zh:"用手机相机扫描", ko:"휴대폰 카메라로 스캔" };
D["Free · Self-custody · No account required to start"] = { es:"Gratis · Auto-custodia · Sin cuenta para empezar", de:"Kostenlos · Selbstverwahrung · Kein Konto nötig", nl:"Gratis · Zelfbeheer · Geen account nodig om te starten", uk:"Безкоштовно · Самозберігання · Без реєстрації для початку", ru:"Бесплатно · Самостоятельное хранение · Аккаунт не нужен", fr:"Gratuit · Auto-conservation · Aucun compte requis", pt:"Grátis · Autocustódia · Sem conta para começar", zh:"免费 · 自托管 · 无需注册即可开始", ko:"무료 · 셀프 커스터디 · 계정 없이 시작" };
D["iPhone & iPad. The full wallet, in your pocket."] = { es:"iPhone y iPad. La wallet completa, en tu bolsillo.", de:"iPhone & iPad. Die volle Wallet in deiner Tasche.", nl:"iPhone & iPad. De volledige wallet, in je zak.", uk:"iPhone та iPad. Повноцінний гаманець у кишені.", ru:"iPhone и iPad. Полноценный кошелёк в кармане.", fr:"iPhone et iPad. Le wallet complet, dans votre poche.", pt:"iPhone e iPad. A carteira completa, no seu bolso.", zh:"iPhone 与 iPad。完整钱包，随身携带。", ko:"iPhone & iPad. 완전한 지갑을 주머니에." };
D["Phones & tablets. Same wallet, same keys."] = { es:"Móviles y tablets. La misma wallet, las mismas claves.", de:"Handys & Tablets. Gleiche Wallet, gleiche Schlüssel.", nl:"Telefoons & tablets. Dezelfde wallet, dezelfde sleutels.", uk:"Телефони та планшети. Той самий гаманець, ті самі ключі.", ru:"Телефоны и планшеты. Тот же кошелёк, те же ключи.", fr:"Téléphones et tablettes. Même wallet, mêmes clés.", pt:"Celulares e tablets. Mesma carteira, mesmas chaves.", zh:"手机与平板。同一个钱包，同一组密钥。", ko:"폰 & 태블릿. 같은 지갑, 같은 키." };
D["Desktop & browser. Open your vaults - nothing to install."] = { es:"Escritorio y navegador. Abre tus vaults sin instalar nada.", de:"Desktop & Browser. Öffne deine Vaults – ohne Installation.", nl:"Desktop & browser. Open je vaults - niets te installeren.", uk:"Комп'ютер і браузер. Відкривайте свої сховища — без встановлення.", ru:"Компьютер и браузер. Открывайте свои хранилища — без установки.", fr:"Bureau et navigateur. Ouvrez vos coffres - rien à installer.", pt:"Desktop e navegador. Abra seus cofres - nada a instalar.", zh:"桌面与浏览器。直接打开金库，无需安装。", ko:"데스크톱 & 브라우저. 설치 없이 볼트를 여세요." };
D["For this device"] = { es:"Para este dispositivo", de:"Für dieses Gerät", nl:"Voor dit apparaat", uk:"Для цього пристрою", ru:"Для этого устройства", fr:"Pour cet appareil", pt:"Para este dispositivo", zh:"适合此设备", ko:"이 기기용" };
D["App Store rating"] = { es:"Valoración en App Store", de:"App-Store-Bewertung", nl:"App Store-beoordeling", uk:"Оцінка в App Store", ru:"Оценка в App Store", fr:"Note App Store", pt:"Avaliação na App Store", zh:"App Store 评分", ko:"App Store 평점" };
D["Five-star ratings"] = { es:"Valoraciones de 5 estrellas", de:"Fünf-Sterne-Bewertungen", nl:"Vijfsterrenbeoordelingen", uk:"П'ятизіркові оцінки", ru:"Пятизвёздочные оценки", fr:"Notes cinq étoiles", pt:"Avaliações 5 estrelas", zh:"五星好评", ko:"5점 리뷰" };

/* ---- swap page ---- */
D["Swap anything."] = { es:"Intercambia lo que quieras.", de:"Tausche alles.", nl:"Swap alles.", uk:"Обмінюйте будь-що.", ru:"Обменивайте что угодно.", fr:"Échangez tout.", pt:"Troque qualquer ativo.", zh:"任意兑换。", ko:"무엇이든 스왑." };
D["Across every chain."] = { es:"En todas las cadenas.", de:"Über jede Chain.", nl:"Over elke chain.", uk:"Через усі мережі.", ru:"Через все сети.", fr:"Sur toutes les chaînes.", pt:"Em todas as redes.", zh:"跨越每一条链。", ko:"모든 체인에서." };
D["More native cross-chain routes than any wallet in crypto. Real BTC for real SOL - no bridges, no wrapped tokens - straight from self-custody."] = { es:"Más rutas cross-chain nativas que cualquier wallet en cripto. BTC real por SOL real, sin bridges ni tokens envueltos, directamente desde la auto-custodia.", de:"Mehr native Cross-Chain-Routen als jede andere Wallet in Krypto. Echtes BTC gegen echtes SOL – ohne Bridges, ohne Wrapped Tokens – direkt aus der Selbstverwahrung.", nl:"Meer native cross-chain routes dan welke wallet dan ook. Echte BTC voor echte SOL - zonder bridges, zonder wrapped tokens - rechtstreeks vanuit zelfbeheer.", uk:"Більше нативних крос-чейн маршрутів, ніж у будь-якого гаманця в криптосвіті. Справжній BTC за справжній SOL — без мостів і wrapped-токенів — прямо з самозберігання.", ru:"Больше нативных кросс-чейн маршрутов, чем у любого кошелька в крипте. Настоящий BTC за настоящий SOL — без мостов и wrapped-токенов — прямо из самостоятельного хранения.", fr:"Plus de routes cross-chain natives que n'importe quel wallet crypto. Du vrai BTC contre du vrai SOL - sans bridges, sans tokens wrappés - directement en auto-conservation.", pt:"Mais rotas cross-chain nativas do que qualquer carteira em cripto. BTC real por SOL real - sem bridges, sem tokens embrulhados - direto da autocustódia.", zh:"加密领域原生跨链路径最多的钱包。真 BTC 换真 SOL——无跨链桥、无封装代币——直接在自托管中完成。", ko:"암호화폐 지갑 중 가장 많은 네이티브 크로스체인 경로. 진짜 BTC를 진짜 SOL로 — 브리지도, 래핑 토큰도 없이 — 셀프 커스터디에서 바로." };
D["Swapped natively since 2021"] = { es:"Intercambiado de forma nativa desde 2021", de:"Nativ getauscht seit 2021", nl:"Native geswapt sinds 2021", uk:"Обміняно нативно з 2021 року", ru:"Обменяно нативно с 2021 года", fr:"Échangé nativement depuis 2021", pt:"Trocado nativamente desde 2021", zh:"自 2021 年以来的原生兑换量", ko:"2021년부터 네이티브 스왑" };
D["Bridges. None. Ever."] = { es:"Bridges. Ninguno. Nunca.", de:"Bridges. Keine. Niemals.", nl:"Bridges. Geen. Nooit.", uk:"Мости. Нуль. Ніколи.", ru:"Мосты. Ноль. Никогда.", fr:"Bridges. Aucun. Jamais.", pt:"Bridges. Nenhuma. Nunca.", zh:"跨链桥？零。永远。", ko:"브리지. 0개. 영원히." };
D["Popular routes"] = { es:"Rutas populares", de:"Beliebte Routen", nl:"Populaire routes", uk:"Популярні маршрути", ru:"Популярные маршруты", fr:"Routes populaires", pt:"Rotas populares", zh:"热门路径", ko:"인기 경로" };
D["Any asset,"] = { es:"Cualquier activo,", de:"Jedes Asset,", nl:"Elk asset,", uk:"Будь-який актив,", ru:"Любой актив,", fr:"Tout actif,", pt:"Qualquer ativo,", zh:"任意资产，", ko:"어떤 자산이든," };
D["any chain."] = { es:"cualquier cadena.", de:"jede Chain.", nl:"elke chain.", uk:"будь-яка мережа.", ru:"любая сеть.", fr:"toute chaîne.", pt:"qualquer rede.", zh:"任意链。", ko:"어떤 체인이든." };
D["One tap from native Bitcoin to native Ethereum or Solana - the asset that arrives is the real thing."] = { es:"Un toque de Bitcoin nativo a Ethereum o Solana nativos: el activo que llega es el de verdad.", de:"Ein Tipp von nativem Bitcoin zu nativem Ethereum oder Solana – was ankommt, ist das Original.", nl:"Eén tik van native Bitcoin naar native Ethereum of Solana - wat aankomt is het echte werk.", uk:"Один дотик — від нативного Bitcoin до нативного Ethereum чи Solana. Прибуває справжній актив.", ru:"Одно касание — от нативного Bitcoin к нативному Ethereum или Solana. Приходит настоящий актив.", fr:"Un seul geste du Bitcoin natif vers l'Ethereum ou le Solana natifs - l'actif qui arrive est le vrai.", pt:"Um toque do Bitcoin nativo ao Ethereum ou Solana nativos - o ativo que chega é o verdadeiro.", zh:"一键从原生比特币到原生以太坊或 Solana——到账的就是真实资产。", ko:"네이티브 비트코인에서 네이티브 이더리움·솔라나까지 한 번의 탭 — 도착하는 자산은 진짜입니다." };
D["Route"] = { es:"Ruta", de:"Route", nl:"Route", uk:"Маршрут", ru:"Маршрут", fr:"Route", pt:"Rota", zh:"路径", ko:"경로" };
D["Native · no bridge"] = { es:"Nativa · sin bridge", de:"Nativ · ohne Bridge", nl:"Native · geen bridge", uk:"Нативний · без моста", ru:"Нативный · без моста", fr:"Native · sans bridge", pt:"Nativa · sem bridge", zh:"原生 · 无跨链桥", ko:"네이티브 · 브리지 없음" };
D["Illustrative rates. Live quotes in the app reflect market prices at execution."] = { es:"Tasas ilustrativas. Las cotizaciones en la app reflejan los precios de mercado al ejecutar.", de:"Beispielkurse. Live-Quotes in der App spiegeln die Marktpreise bei Ausführung wider.", nl:"Illustratieve koersen. Live quotes in de app volgen de marktprijzen bij uitvoering.", uk:"Ілюстративні курси. Живі котирування в застосунку відображають ринкові ціни на момент виконання.", ru:"Иллюстративные курсы. Живые котировки в приложении отражают рыночные цены на момент исполнения.", fr:"Taux indicatifs. Les cotations en direct dans l'app reflètent les prix du marché à l'exécution.", pt:"Taxas ilustrativas. As cotações ao vivo no app refletem os preços de mercado na execução.", zh:"示例汇率。应用内实时报价以执行时的市场价格为准。", ko:"예시 환율입니다. 앱의 실시간 시세는 실행 시점의 시장 가격을 반영합니다." };
D["Pick any pair"] = { es:"Elige cualquier par", de:"Wähle ein beliebiges Paar", nl:"Kies elk paar", uk:"Оберіть будь-яку пару", ru:"Выберите любую пару", fr:"Choisissez n'importe quelle paire", pt:"Escolha qualquer par", zh:"任选交易对", ko:"아무 페어나 선택" };
D["BTC to SOL, ETH to stablecoins - 20,000+ tokens, one balance, one app."] = { es:"De BTC a SOL, de ETH a stablecoins: más de 20.000 tokens, un saldo, una app.", de:"BTC zu SOL, ETH zu Stablecoins – über 20.000 Tokens, ein Guthaben, eine App.", nl:"BTC naar SOL, ETH naar stablecoins - 20.000+ tokens, één saldo, één app.", uk:"BTC у SOL, ETH у стейблкоїни — понад 20 000 токенів, один баланс, один застосунок.", ru:"BTC в SOL, ETH в стейблкоины — более 20 000 токенов, один баланс, одно приложение.", fr:"BTC vers SOL, ETH vers stablecoins - plus de 20 000 tokens, un solde, une app.", pt:"BTC para SOL, ETH para stablecoins - mais de 20.000 tokens, um saldo, um app.", zh:"BTC 换 SOL、ETH 换稳定币——20,000+ 代币，一个余额，一个应用。", ko:"BTC에서 SOL로, ETH에서 스테이블코인으로 — 20,000+ 토큰, 하나의 잔고, 하나의 앱." };
D["Best route, found"] = { es:"La mejor ruta, encontrada", de:"Beste Route, gefunden", nl:"Beste route, gevonden", uk:"Найкращий маршрут знайдено", ru:"Лучший маршрут найден", fr:"Meilleure route, trouvée", pt:"Melhor rota, encontrada", zh:"自动找到最优路径", ko:"최적 경로 자동 탐색" };
D["Aggregated liquidity finds the best rate automatically - gasless on supported routes."] = { es:"La liquidez agregada encuentra el mejor precio automáticamente, sin gas en rutas compatibles.", de:"Aggregierte Liquidität findet automatisch den besten Kurs – gaslos auf unterstützten Routen.", nl:"Geaggregeerde liquiditeit vindt automatisch de beste koers - gasloos op ondersteunde routes.", uk:"Агрегована ліквідність автоматично знаходить найкращий курс — без газу на підтримуваних маршрутах.", ru:"Агрегированная ликвидность автоматически находит лучший курс — без газа на поддерживаемых маршрутах.", fr:"La liquidité agrégée trouve automatiquement le meilleur taux - sans gas sur les routes prises en charge.", pt:"A liquidez agregada encontra a melhor taxa automaticamente - sem gás em rotas compatíveis.", zh:"聚合流动性自动找到最优汇率——受支持路径免 Gas。", ko:"애그리게이트 유동성이 자동으로 최적 환율을 찾습니다 — 지원 경로에서는 가스리스." };
D["Native settlement"] = { es:"Liquidación nativa", de:"Native Abwicklung", nl:"Native afwikkeling", uk:"Нативний розрахунок", ru:"Нативный расчёт", fr:"Règlement natif", pt:"Liquidação nativa", zh:"原生结算", ko:"네이티브 정산" };
D["Real assets arrive on the destination chain. No bridges, no wrapped tokens, no IOUs."] = { es:"Los activos reales llegan a la cadena de destino. Sin bridges, sin tokens envueltos, sin pagarés.", de:"Echte Assets kommen auf der Ziel-Chain an. Keine Bridges, keine Wrapped Tokens, keine IOUs.", nl:"Echte assets komen aan op de bestemmingschain. Geen bridges, geen wrapped tokens, geen IOU's.", uk:"Справжні активи надходять у цільову мережу. Без мостів, wrapped-токенів і боргових розписок.", ru:"Настоящие активы поступают в целевую сеть. Без мостов, wrapped-токенов и долговых расписок.", fr:"Les vrais actifs arrivent sur la chaîne de destination. Sans bridges, sans tokens wrappés, sans reconnaissances de dette.", pt:"Ativos reais chegam à rede de destino. Sem bridges, sem tokens embrulhados, sem IOUs.", zh:"真实资产抵达目标链。无跨链桥、无封装代币、无欠条。", ko:"진짜 자산이 목적지 체인에 도착합니다. 브리지·래핑 토큰·차용증 없음." };
D["Your fee."] = { es:"Tu comisión.", de:"Deine Gebühr.", nl:"Jouw fee.", uk:"Ваша комісія.", ru:"Ваша комиссия.", fr:"Vos frais.", pt:"Sua taxa.", zh:"你的费率。", ko:"수수료는" };
D["Your call."] = { es:"Tú decides.", de:"Deine Entscheidung.", nl:"Jij beslist.", uk:"Ваш вибір.", ru:"Ваш выбор.", fr:"Votre choix.", pt:"Você decide.", zh:"由你决定。", ko:"당신이 정합니다." };
D["Swaps under $100 are free. Stake $TITN to cut your fee to as low as 0.2% - and earn up to ~70% of it back in USDC."] = { es:"Los swaps de menos de $100 son gratis. Haz staking de $TITN para reducir tu comisión hasta el 0,2% y recupera hasta ~70% en USDC.", de:"Swaps unter 100 $ sind kostenlos. Stake $TITN, um deine Gebühr auf bis zu 0,2 % zu senken – und erhalte bis zu ~70 % davon in USDC zurück.", nl:"Swaps onder $100 zijn gratis. Stake $TITN om je fee te verlagen tot 0,2% - en verdien tot ~70% ervan terug in USDC.", uk:"Обміни до $100 — безкоштовні. Стейкайте $TITN, щоб знизити комісію до 0,2% і повертати до ~70% у USDC.", ru:"Обмены до $100 — бесплатны. Стейкайте $TITN, чтобы снизить комиссию до 0,2% и возвращать до ~70% в USDC.", fr:"Les swaps de moins de 100 $ sont gratuits. Stakez $TITN pour réduire vos frais jusqu'à 0,2 % - et récupérez jusqu'à ~70 % en USDC.", pt:"Swaps abaixo de $100 são grátis. Faça staking de $TITN para reduzir sua taxa até 0,2% - e receba até ~70% de volta em USDC.", zh:"100 美元以下兑换免费。质押 $TITN 可将费率降至 0.2%，并以 USDC 形式返还最高约 70%。", ko:"$100 미만 스왑은 무료입니다. $TITN을 스테이킹하면 수수료가 최저 0.2%까지 내려가고, 최대 약 70%를 USDC로 돌려받습니다." };
D["Bigger trades unlock further automatic discounts."] = { es:"Las operaciones más grandes desbloquean descuentos automáticos adicionales.", de:"Größere Trades schalten weitere automatische Rabatte frei.", nl:"Grotere trades ontgrendelen extra automatische kortingen.", uk:"Більші угоди відкривають додаткові автоматичні знижки.", ru:"Более крупные сделки открывают дополнительные автоматические скидки.", fr:"Les transactions plus importantes débloquent des remises automatiques supplémentaires.", pt:"Negociações maiores desbloqueiam descontos automáticos adicionais.", zh:"交易额越大，自动享受的折扣越多。", ko:"거래 규모가 클수록 자동 할인 폭이 커집니다." };
D["See all tiers & rebates →"] = { es:"Ver todos los niveles y reembolsos →", de:"Alle Stufen & Rückvergütungen ansehen →", nl:"Bekijk alle niveaus & rebates →", uk:"Усі рівні та відшкодування →", ru:"Все уровни и возвраты →", fr:"Voir tous les niveaux et remises →", pt:"Ver todos os níveis e rebates →", zh:"查看全部等级与返还 →", ko:"모든 등급 및 리베이트 보기 →" };
D["Swap questions, answered."] = { es:"Preguntas sobre swaps, respondidas.", de:"Swap-Fragen, beantwortet.", nl:"Swapvragen, beantwoord.", uk:"Відповіді на запитання про обміни.", ru:"Ответы на вопросы об обменах.", fr:"Vos questions sur les swaps, résolues.", pt:"Perguntas sobre swaps, respondidas.", zh:"兑换常见问题解答。", ko:"스왑 관련 질문과 답변." };
D["Are the swaps really native?"] = { es:"¿Los swaps son realmente nativos?", de:"Sind die Swaps wirklich nativ?", nl:"Zijn de swaps echt native?", uk:"Обміни справді нативні?", ru:"Обмены действительно нативные?", fr:"Les swaps sont-ils vraiment natifs ?", pt:"Os swaps são realmente nativos?", zh:"兑换真的是原生的吗？", ko:"스왑이 정말 네이티브인가요?" };
D["Yes. You send real BTC and receive real SOL on the destination chain. No bridges, no wrapped tokens - which means no bridge risk."] = { es:"Sí. Envías BTC real y recibes SOL real en la cadena de destino. Sin bridges ni tokens envueltos, lo que significa cero riesgo de bridge.", de:"Ja. Du sendest echtes BTC und erhältst echtes SOL auf der Ziel-Chain. Keine Bridges, keine Wrapped Tokens – also kein Bridge-Risiko.", nl:"Ja. Je verstuurt echte BTC en ontvangt echte SOL op de bestemmingschain. Geen bridges, geen wrapped tokens - dus geen bridgerisico.", uk:"Так. Ви надсилаєте справжній BTC і отримуєте справжній SOL у цільовій мережі. Без мостів і wrapped-токенів — отже, без ризику мостів.", ru:"Да. Вы отправляете настоящий BTC и получаете настоящий SOL в целевой сети. Без мостов и wrapped-токенов — а значит, без риска мостов.", fr:"Oui. Vous envoyez du vrai BTC et recevez du vrai SOL sur la chaîne de destination. Sans bridges ni tokens wrappés - donc aucun risque de bridge.", pt:"Sim. Você envia BTC real e recebe SOL real na rede de destino. Sem bridges, sem tokens embrulhados - ou seja, sem risco de bridge.", zh:"是的。您发送真实 BTC，在目标链上收到真实 SOL。无跨链桥、无封装代币——因此没有跨链桥风险。", ko:"네. 진짜 BTC를 보내고 목적지 체인에서 진짜 SOL을 받습니다. 브리지와 래핑 토큰이 없으니 브리지 리스크도 없습니다." };
D["What do swaps cost?"] = { es:"¿Cuánto cuestan los swaps?", de:"Was kosten Swaps?", nl:"Wat kosten swaps?", uk:"Скільки коштують обміни?", ru:"Сколько стоят обмены?", fr:"Combien coûtent les swaps ?", pt:"Quanto custam os swaps?", zh:"兑换费用是多少？", ko:"스왑 비용은 얼마인가요?" };
D["Swaps under $100 are free. Above that, 0.2–1.25% depending on your $TITN staking tier - and stakers earn up to ~70% of fees back in USDC. Larger transactions unlock automatic volume discounts."] = { es:"Los swaps de menos de $100 son gratis. Por encima, del 0,2% al 1,25% según tu nivel de staking de $TITN, y los stakers recuperan hasta ~70% de las comisiones en USDC. Las operaciones grandes desbloquean descuentos automáticos por volumen.", de:"Swaps unter 100 $ sind kostenlos. Darüber 0,2–1,25 % je nach $TITN-Staking-Stufe – Staker erhalten bis zu ~70 % der Gebühren in USDC zurück. Größere Transaktionen schalten automatische Volumenrabatte frei.", nl:"Swaps onder $100 zijn gratis. Daarboven 0,2–1,25% afhankelijk van je $TITN-stakingniveau - stakers verdienen tot ~70% van de fees terug in USDC. Grotere transacties ontgrendelen automatische volumekortingen.", uk:"Обміни до $100 — безкоштовні. Понад це — 0,2–1,25% залежно від рівня стейкінгу $TITN; стейкери повертають до ~70% комісій у USDC. Великі транзакції відкривають автоматичні знижки за обсяг.", ru:"Обмены до $100 — бесплатны. Выше — 0,2–1,25% в зависимости от уровня стейкинга $TITN; стейкеры возвращают до ~70% комиссий в USDC. Крупные транзакции открывают автоматические скидки за объём.", fr:"Les swaps de moins de 100 $ sont gratuits. Au-delà, 0,2–1,25 % selon votre niveau de staking $TITN - les stakers récupèrent jusqu'à ~70 % des frais en USDC. Les grosses transactions débloquent des remises automatiques.", pt:"Swaps abaixo de $100 são grátis. Acima disso, 0,2–1,25% conforme seu nível de staking de $TITN - stakers recebem até ~70% das taxas de volta em USDC. Transações maiores desbloqueiam descontos automáticos por volume.", zh:"100 美元以下兑换免费。超出部分按 $TITN 质押等级收取 0.2–1.25%，质押者可获最高约 70% 的 USDC 费用返还。大额交易自动享受交易量折扣。", ko:"$100 미만 스왑은 무료입니다. 그 이상은 $TITN 스테이킹 등급에 따라 0.2–1.25%이며, 스테이커는 수수료의 최대 약 70%를 USDC로 돌려받습니다. 대규모 거래는 자동 거래량 할인이 적용됩니다." };
D["Do I need gas tokens on every chain?"] = { es:"¿Necesito tokens de gas en cada cadena?", de:"Brauche ich Gas-Tokens auf jeder Chain?", nl:"Heb ik gastokens nodig op elke chain?", uk:"Чи потрібні газові токени в кожній мережі?", ru:"Нужны ли газовые токены в каждой сети?", fr:"Ai-je besoin de tokens de gas sur chaque chaîne ?", pt:"Preciso de tokens de gás em cada rede?", zh:"每条链都需要 Gas 代币吗？", ko:"체인마다 가스 토큰이 필요한가요?" };
D["Not on supported routes - swaps there are gasless, so you don't need to hold the destination chain's native token before you receive funds on it."] = { es:"No en las rutas compatibles: allí los swaps son sin gas, así que no necesitas el token nativo de la cadena de destino antes de recibir fondos.", de:"Nicht auf unterstützten Routen – dort sind Swaps gaslos, du brauchst den nativen Token der Ziel-Chain also nicht im Voraus.", nl:"Niet op ondersteunde routes - daar zijn swaps gasloos, dus je hoeft de native token van de bestemmingschain niet vooraf te bezitten.", uk:"Не на підтримуваних маршрутах — там обміни без газу, тож вам не потрібен нативний токен цільової мережі заздалегідь.", ru:"Не на поддерживаемых маршрутах — там обмены без газа, поэтому нативный токен целевой сети заранее не нужен.", fr:"Pas sur les routes prises en charge - les swaps y sont sans gas, vous n'avez donc pas besoin du token natif de la chaîne de destination au préalable.", pt:"Não nas rotas compatíveis - lá os swaps são sem gás, então você não precisa do token nativo da rede de destino antes de receber fundos.", zh:"受支持的路径不需要——这些路径免 Gas，您无需提前持有目标链的原生代币。", ko:"지원 경로에서는 필요 없습니다. 가스리스 스왑이므로 목적지 체인의 네이티브 토큰을 미리 보유하지 않아도 됩니다." };
D["Which tokens can I swap?"] = { es:"¿Qué tokens puedo intercambiar?", de:"Welche Tokens kann ich tauschen?", nl:"Welke tokens kan ik swappen?", uk:"Які токени можна обмінювати?", ru:"Какие токены можно обменивать?", fr:"Quels tokens puis-je échanger ?", pt:"Quais tokens posso trocar?", zh:"可以兑换哪些代币？", ko:"어떤 토큰을 스왑할 수 있나요?" };
D["20,000+ tokens across every major chain - Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain and more - with best-rate routing across aggregated liquidity."] = { es:"Más de 20.000 tokens en todas las cadenas principales (Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain y más) con enrutamiento al mejor precio sobre liquidez agregada.", de:"Über 20.000 Tokens über alle großen Chains – Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain und mehr – mit Bestkurs-Routing über aggregierte Liquidität.", nl:"20.000+ tokens op elke grote chain - Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain en meer - met best-rate routing over geaggregeerde liquiditeit.", uk:"Понад 20 000 токенів на всіх основних мережах — Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain та інших — з маршрутизацією за найкращим курсом через агреговану ліквідність.", ru:"Более 20 000 токенов во всех основных сетях — Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain и других — с маршрутизацией по лучшему курсу через агрегированную ликвидность.", fr:"Plus de 20 000 tokens sur toutes les grandes chaînes - Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain et plus - avec routage au meilleur taux sur liquidité agrégée.", pt:"Mais de 20.000 tokens em todas as principais redes - Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain e mais - com roteamento à melhor taxa sobre liquidez agregada.", zh:"覆盖所有主流链的 20,000+ 代币——比特币、以太坊、Solana、BNB Chain、Stellar、Sui、Cosmos、THORChain 等——通过聚合流动性实现最优汇率路由。", ko:"모든 주요 체인의 20,000+ 토큰 — Bitcoin, Ethereum, Solana, BNB Chain, Stellar, Sui, Cosmos, THORChain 등 — 애그리게이트 유동성 기반 최적 환율 라우팅." };
D["Swap natively."] = { es:"Intercambia de forma nativa.", de:"Tausche nativ.", nl:"Swap native.", uk:"Обмінюйте нативно.", ru:"Обменивайте нативно.", fr:"Échangez nativement.", pt:"Troque nativamente.", zh:"原生兑换。", ko:"네이티브로 스왑하세요." };
D["Every chain, one app, your keys."] = { es:"Todas las cadenas, una app, tus claves.", de:"Jede Chain, eine App, deine Schlüssel.", nl:"Elke chain, één app, jouw sleutels.", uk:"Усі мережі, один застосунок, ваші ключі.", ru:"Все сети, одно приложение, ваши ключи.", fr:"Toutes les chaînes, une app, vos clés.", pt:"Todas as redes, um app, suas chaves.", zh:"每条链，一个应用，你的密钥。", ko:"모든 체인, 하나의 앱, 당신의 키." };
D["Get THORWallet"] = { es:"Descarga THORWallet", de:"Hol dir THORWallet", nl:"Download THORWallet", uk:"Завантажити THORWallet", ru:"Скачать THORWallet", fr:"Téléchargez THORWallet", pt:"Baixe a THORWallet", zh:"获取 THORWallet", ko:"THORWallet 받기" };
D["Open the Web App"] = { es:"Abrir la app web", de:"Web-App öffnen", nl:"Open de web-app", uk:"Відкрити веб-додаток", ru:"Открыть веб-приложение", fr:"Ouvrir l'app web", pt:"Abrir o app web", zh:"打开网页应用", ko:"웹 앱 열기" };

/* ---- compare pages ---- */
D["vs. the rest."] = { es:"contra el resto.", de:"vs. der Rest.", nl:"vs. de rest.", uk:"проти решти.", ru:"против остальных.", fr:"vs le reste.", pt:"vs. o resto.", zh:"对比其余所有。", ko:"vs. 나머지 전부." };
D["Every wallet says it's the best. Here's the honest, side-by-side version - what THORWallet does that others don't, and where the others genuinely shine."] = { es:"Todas las wallets dicen ser la mejor. Aquí está la versión honesta, lado a lado: lo que THORWallet hace y otras no, y dónde las otras realmente destacan.", de:"Jede Wallet nennt sich die beste. Hier der ehrliche Direktvergleich – was THORWallet kann und andere nicht, und wo andere wirklich glänzen.", nl:"Elke wallet noemt zichzelf de beste. Hier is de eerlijke vergelijking - wat THORWallet doet en anderen niet, en waar de anderen echt uitblinken.", uk:"Кожен гаманець називає себе найкращим. Ось чесне порівняння — що вміє THORWallet і не вміють інші, та в чому інші справді сильні.", ru:"Каждый кошелёк называет себя лучшим. Вот честное сравнение — что умеет THORWallet и не умеют другие, и в чём другие действительно сильны.", fr:"Chaque wallet se dit le meilleur. Voici la version honnête, côte à côte - ce que THORWallet fait que les autres ne font pas, et où les autres brillent vraiment.", pt:"Toda carteira diz ser a melhor. Aqui está a versão honesta, lado a lado - o que a THORWallet faz que as outras não fazem, e onde as outras realmente brilham.", zh:"每个钱包都说自己最好。这里是诚实的对比：THORWallet 能做而别人做不到的，以及别人真正出色的地方。", ko:"모든 지갑이 자기가 최고라고 말합니다. 여기 정직한 비교가 있습니다 — THORWallet만 할 수 있는 것과, 다른 지갑이 진짜 잘하는 것." };
D["Feature"] = { es:"Función", de:"Funktion", nl:"Functie", uk:"Функція", ru:"Функция", fr:"Fonction", pt:"Recurso", zh:"功能", ko:"기능" };
D["Cross-chain swaps without bridges"] = { es:"Swaps cross-chain sin bridges", de:"Cross-Chain-Swaps ohne Bridges", nl:"Cross-chain swaps zonder bridges", uk:"Крос-чейн обміни без мостів", ru:"Кросс-чейн обмены без мостов", fr:"Swaps cross-chain sans bridges", pt:"Swaps cross-chain sem bridges", zh:"无桥跨链兑换", ko:"브리지 없는 크로스체인 스왑" };
D["Native cross-chain routes"] = { es:"Rutas cross-chain nativas", de:"Native Cross-Chain-Routen", nl:"Native cross-chain routes", uk:"Нативні крос-чейн маршрути", ru:"Нативные кросс-чейн маршруты", fr:"Routes cross-chain natives", pt:"Rotas cross-chain nativas", zh:"原生跨链路径", ko:"네이티브 크로스체인 경로" };
D["Most in crypto"] = { es:"Las más de cripto", de:"Die meisten in Krypto", nl:"Meeste in crypto", uk:"Найбільше в крипті", ru:"Больше всех в крипте", fr:"Le plus en crypto", pt:"Mais de toda a cripto", zh:"加密领域最多", ko:"업계 최다" };
D["Most in crypto, for native assets"] = { es:"Las más de cripto, para activos nativos", de:"Die meisten in Krypto, für native Assets", nl:"Meeste in crypto, voor native assets", uk:"Найбільше в крипті для нативних активів", ru:"Больше всех в крипте для нативных активов", fr:"Le plus en crypto, pour les actifs natifs", pt:"Mais de toda a cripto, para ativos nativos", zh:"原生资产跨链路径业界最多", ko:"네이티브 자산 기준 업계 최다" };
D["Limited"] = { es:"Limitado", de:"Begrenzt", nl:"Beperkt", uk:"Обмежено", ru:"Ограничено", fr:"Limité", pt:"Limitado", zh:"有限", ko:"제한적" };
D["Bridge-based"] = { es:"Basado en bridges", de:"Bridge-basiert", nl:"Via bridges", uk:"Через мости", ru:"Через мосты", fr:"Via bridges", pt:"Baseado em bridges", zh:"依赖跨链桥", ko:"브리지 기반" };
D["Aggregator-based"] = { es:"Basado en agregadores", de:"Aggregator-basiert", nl:"Via aggregators", uk:"Через агрегатори", ru:"Через агрегаторы", fr:"Via agrégateurs", pt:"Baseado em agregadores", zh:"依赖聚合器", ko:"애그리게이터 기반" };
D["Tokens supported"] = { es:"Tokens compatibles", de:"Unterstützte Tokens", nl:"Ondersteunde tokens", uk:"Підтримувані токени", ru:"Поддерживаемые токены", fr:"Tokens pris en charge", pt:"Tokens suportados", zh:"支持的代币", ko:"지원 토큰" };
D["Fee rebates"] = { es:"Reembolso de comisiones", de:"Gebühren-Rückvergütung", nl:"Fee-rebates", uk:"Відшкодування комісій", ru:"Возврат комиссий", fr:"Remise sur frais", pt:"Rebate de taxas", zh:"费用返还", ko:"수수료 리베이트" };
D["Up to ~70% in USDC"] = { es:"Hasta ~70% en USDC", de:"Bis zu ~70 % in USDC", nl:"Tot ~70% in USDC", uk:"До ~70% у USDC", ru:"До ~70% в USDC", fr:"Jusqu'à ~70 % en USDC", pt:"Até ~70% em USDC", zh:"最高约 70%，以 USDC 返还", ko:"최대 약 70%를 USDC로" };
D["Up to ~70% back in USDC"] = { es:"Hasta ~70% de vuelta en USDC", de:"Bis zu ~70 % zurück in USDC", nl:"Tot ~70% terug in USDC", uk:"До ~70% повернення в USDC", ru:"До ~70% возврата в USDC", fr:"Jusqu'à ~70 % récupérés en USDC", pt:"Até ~70% de volta em USDC", zh:"最高约 70% 以 USDC 返还", ko:"최대 약 70% USDC로 환급" };
D["Yes, even cross-chain"] = { es:"Sí, incluso cross-chain", de:"Ja, sogar cross-chain", nl:"Ja, zelfs cross-chain", uk:"Так, навіть крос-чейн", ru:"Да, даже кросс-чейн", fr:"Oui, même cross-chain", pt:"Sim, até cross-chain", zh:"支持，甚至跨链", ko:"네, 크로스체인까지" };
D["Yes, on swaps"] = { es:"Sí, en swaps", de:"Ja, bei Swaps", nl:"Ja, bij swaps", uk:"Так, в обмінах", ru:"Да, в обменах", fr:"Oui, sur les swaps", pt:"Sim, em swaps", zh:"支持（限兑换）", ko:"네, 스왑에서" };
D["Yes"] = { es:"Sí", de:"Ja", nl:"Ja", uk:"Так", ru:"Да", fr:"Oui", pt:"Sim", zh:"支持", ko:"예" };
D["Yes, 24/7"] = { es:"Sí, 24/7", de:"Ja, rund um die Uhr", nl:"Ja, 24/7", uk:"Так, 24/7", ru:"Да, 24/7", fr:"Oui, 24h/24", pt:"Sim, 24/7", zh:"支持，全天候", ko:"네, 24시간" };
D["Equity perps only"] = { es:"Solo perps de acciones", de:"Nur Aktien-Perps", nl:"Alleen aandelen-perps", uk:"Лише perps на акції", ru:"Только perps на акции", fr:"Perps actions uniquement", pt:"Apenas perps de ações", zh:"仅股票永续合约", ko:"주식 무기한 계약만" };
D["Multisig vaults"] = { es:"Vaults multifirma", de:"Multisig-Vaults", nl:"Multisig-vaults", uk:"Мультипідписні сховища", ru:"Мультиподписные хранилища", fr:"Coffres multisig", pt:"Cofres multisig", zh:"多签金库", ko:"멀티시그 볼트" };
D["Any chain & token"] = { es:"Cualquier cadena y token", de:"Jede Chain & jeder Token", nl:"Elke chain & token", uk:"Будь-яка мережа і токен", ru:"Любая сеть и токен", fr:"Toute chaîne et token", pt:"Qualquer rede e token", zh:"任意链与代币", ko:"모든 체인 & 토큰" };
D["Crypto card"] = { es:"Tarjeta cripto", de:"Krypto-Karte", nl:"Cryptokaart", uk:"Криптокартка", ru:"Криптокарта", fr:"Carte crypto", pt:"Cartão cripto", zh:"加密卡", ko:"크립토 카드" };
D["Mastercard, 175+ countries"] = { es:"Mastercard, más de 175 países", de:"Mastercard, über 175 Länder", nl:"Mastercard, 175+ landen", uk:"Mastercard, понад 175 країн", ru:"Mastercard, более 175 стран", fr:"Mastercard, plus de 175 pays", pt:"Mastercard, mais de 175 países", zh:"Mastercard，175+ 国家", ko:"Mastercard, 175개국 이상" };
D["Limited regions"] = { es:"Regiones limitadas", de:"Begrenzte Regionen", nl:"Beperkte regio's", uk:"Обмежені регіони", ru:"Ограниченные регионы", fr:"Régions limitées", pt:"Regiões limitadas", zh:"仅限部分地区", ko:"일부 지역만" };
D["Bank account (IBAN)"] = { es:"Cuenta bancaria (IBAN)", de:"Bankkonto (IBAN)", nl:"Bankrekening (IBAN)", uk:"Банківський рахунок (IBAN)", ru:"Банковский счёт (IBAN)", fr:"Compte bancaire (IBAN)", pt:"Conta bancária (IBAN)", zh:"银行账户（IBAN）", ko:"은행 계좌(IBAN)" };
D["Swiss IBAN & SEPA"] = { es:"IBAN suizo y SEPA", de:"Schweizer IBAN & SEPA", nl:"Zwitserse IBAN & SEPA", uk:"Швейцарський IBAN та SEPA", ru:"Швейцарский IBAN и SEPA", fr:"IBAN suisse et SEPA", pt:"IBAN suíço e SEPA", zh:"瑞士 IBAN 与 SEPA", ko:"스위스 IBAN & SEPA" };
D["In-app support"] = { es:"Soporte en la app", de:"Support in der App", nl:"Support in de app", uk:"Підтримка в застосунку", ru:"Поддержка в приложении", fr:"Support dans l'app", pt:"Suporte no app", zh:"应用内客服", ko:"앱 내 지원" };
D["24/7 chat, in the app"] = { es:"Chat 24/7, en la app", de:"24/7-Chat in der App", nl:"24/7 chat, in de app", uk:"Чат 24/7 у застосунку", ru:"Чат 24/7 в приложении", fr:"Chat 24h/24, dans l'app", pt:"Chat 24/7, no app", zh:"应用内 24/7 在线客服", ko:"앱 내 24시간 채팅" };
D["Help centre · paid priority"] = { es:"Centro de ayuda · prioridad de pago", de:"Hilfecenter · bezahlte Priorität", nl:"Helpcentrum · betaalde prioriteit", uk:"Довідковий центр · платний пріоритет", ru:"Справочный центр · платный приоритет", fr:"Centre d'aide · priorité payante", pt:"Central de ajuda · prioridade paga", zh:"帮助中心 · 付费优先", ko:"헬프 센터 · 유료 우선 지원" };
D["Help centre"] = { es:"Centro de ayuda", de:"Hilfecenter", nl:"Helpcentrum", uk:"Довідковий центр", ru:"Справочный центр", fr:"Centre d'aide", pt:"Central de ajuda", zh:"帮助中心", ko:"헬프 센터" };
D["= where THORWallet leads. Based on public documentation, June 2026.²"] = { es:"= donde THORWallet lidera. Basado en documentación pública, junio de 2026.²", de:"= wo THORWallet führt. Basierend auf öffentlicher Dokumentation, Juni 2026.²", nl:"= waar THORWallet voorop loopt. Op basis van publieke documentatie, juni 2026.²", uk:"= де THORWallet попереду. На основі публічної документації, червень 2026.²", ru:"= где THORWallet впереди. По данным публичной документации, июнь 2026.²", fr:"= là où THORWallet est en tête. Selon la documentation publique, juin 2026.²", pt:"= onde a THORWallet lidera. Com base em documentação pública, junho de 2026.²", zh:"= THORWallet 领先之处。基于公开文档，2026 年 6 月。²", ko:"= THORWallet이 앞서는 항목. 공개 문서 기준, 2026년 6월.²" };
D["Full comparison →"] = { es:"Comparación completa →", de:"Vollständiger Vergleich →", nl:"Volledige vergelijking →", uk:"Повне порівняння →", ru:"Полное сравнение →", fr:"Comparaison complète →", pt:"Comparação completa →", zh:"查看完整对比 →", ko:"전체 비교 보기 →" };
D["Try the difference."] = { es:"Prueba la diferencia.", de:"Erlebe den Unterschied.", nl:"Ervaar het verschil.", uk:"Відчуйте різницю.", ru:"Почувствуйте разницу.", fr:"Essayez la différence.", pt:"Experimente a diferença.", zh:"亲自体验差别。", ko:"차이를 경험해 보세요." };
D["Native swaps, multisig, and a Swiss account - in one app."] = { es:"Swaps nativos, multifirma y una cuenta suiza, en una sola app.", de:"Native Swaps, Multisig und ein Schweizer Konto – in einer App.", nl:"Native swaps, multisig en een Zwitserse rekening - in één app.", uk:"Нативні обміни, мультипідпис і швейцарський рахунок — в одному застосунку.", ru:"Нативные обмены, мультиподпись и швейцарский счёт — в одном приложении.", fr:"Swaps natifs, multisig et compte suisse - dans une seule app.", pt:"Swaps nativos, multisig e uma conta suíça - em um só app.", zh:"原生兑换、多签、瑞士账户——尽在一个应用。", ko:"네이티브 스왑, 멀티시그, 스위스 계좌 — 하나의 앱에." };
D["vs. MetaMask."] = { es:"vs. MetaMask.", de:"vs. MetaMask.", nl:"vs. MetaMask.", uk:"проти MetaMask.", ru:"против MetaMask.", fr:"vs MetaMask.", pt:"vs. MetaMask.", zh:"对比 MetaMask。", ko:"vs. MetaMask." };
D["vs. Trust Wallet."] = { es:"vs. Trust Wallet.", de:"vs. Trust Wallet.", nl:"vs. Trust Wallet.", uk:"проти Trust Wallet.", ru:"против Trust Wallet.", fr:"vs Trust Wallet.", pt:"vs. Trust Wallet.", zh:"对比 Trust Wallet。", ko:"vs. Trust Wallet." };
D["Where THORWallet wins"] = { es:"Dónde gana THORWallet", de:"Wo THORWallet gewinnt", nl:"Waar THORWallet wint", uk:"Де перемагає THORWallet", ru:"Где побеждает THORWallet", fr:"Où THORWallet gagne", pt:"Onde a THORWallet vence", zh:"THORWallet 的优势", ko:"THORWallet이 이기는 부분" };
D["Where MetaMask wins"] = { es:"Dónde gana MetaMask", de:"Wo MetaMask gewinnt", nl:"Waar MetaMask wint", uk:"Де перемагає MetaMask", ru:"Где побеждает MetaMask", fr:"Où MetaMask gagne", pt:"Onde a MetaMask vence", zh:"MetaMask 的优势", ko:"MetaMask이 이기는 부분" };
D["Where Trust Wallet wins"] = { es:"Dónde gana Trust Wallet", de:"Wo Trust Wallet gewinnt", nl:"Waar Trust Wallet wint", uk:"Де перемагає Trust Wallet", ru:"Где побеждает Trust Wallet", fr:"Où Trust Wallet gagne", pt:"Onde a Trust Wallet vence", zh:"Trust Wallet 的优势", ko:"Trust Wallet이 이기는 부분" };
D["Native settlement - no bridges, no wrapped tokens"] = { es:"Liquidación nativa: sin bridges ni tokens envueltos", de:"Native Abwicklung – ohne Bridges, ohne Wrapped Tokens", nl:"Native afwikkeling - geen bridges, geen wrapped tokens", uk:"Нативний розрахунок — без мостів і wrapped-токенів", ru:"Нативный расчёт — без мостов и wrapped-токенов", fr:"Règlement natif - sans bridges ni tokens wrappés", pt:"Liquidação nativa - sem bridges, sem tokens embrulhados", zh:"原生结算——无跨链桥、无封装代币", ko:"네이티브 정산 — 브리지·래핑 토큰 없음" };
D["Bridging built into swaps"] = { es:"Bridges integrados en los swaps", de:"Bridging in Swaps integriert", nl:"Bridging ingebouwd in swaps", uk:"Мости вбудовано в обміни", ru:"Мосты встроены в обмены", fr:"Bridging intégré aux swaps", pt:"Bridging embutido nos swaps", zh:"兑换内置跨链桥", ko:"스왑에 브리지 내장" };
D["DEX aggregators per chain"] = { es:"Agregadores DEX por cadena", de:"DEX-Aggregatoren pro Chain", nl:"DEX-aggregators per chain", uk:"DEX-агрегатори для кожної мережі", ru:"DEX-агрегаторы для каждой сети", fr:"Agrégateurs DEX par chaîne", pt:"Agregadores DEX por rede", zh:"按链使用 DEX 聚合器", ko:"체인별 DEX 애그리게이터" };
D["20,000+ tokens across every major chain"] = { es:"Más de 20.000 tokens en todas las cadenas principales", de:"Über 20.000 Tokens über alle großen Chains", nl:"20.000+ tokens op elke grote chain", uk:"Понад 20 000 токенів на всіх основних мережах", ru:"Более 20 000 токенов во всех основных сетях", fr:"Plus de 20 000 tokens sur toutes les grandes chaînes", pt:"Mais de 20.000 tokens em todas as principais redes", zh:"覆盖所有主流链的 20,000+ 代币", ko:"모든 주요 체인의 20,000+ 토큰" };
D["100+ chains, millions of tokens"] = { es:"Más de 100 cadenas, millones de tokens", de:"Über 100 Chains, Millionen Tokens", nl:"100+ chains, miljoenen tokens", uk:"Понад 100 мереж, мільйони токенів", ru:"Более 100 сетей, миллионы токенов", fr:"Plus de 100 chaînes, des millions de tokens", pt:"Mais de 100 redes, milhões de tokens", zh:"100+ 条链，数百万代币", ko:"100+ 체인, 수백만 토큰" };
D["No flat fee · ~0.5–1% DEX spread + provider costs"] = { es:"Sin comisión fija · ~0,5–1% de spread DEX + costes de proveedor", de:"Keine Fixgebühr · ~0,5–1 % DEX-Spread + Anbieterkosten", nl:"Geen vaste fee · ~0,5–1% DEX-spread + providerkosten", uk:"Без фіксованої комісії · ~0,5–1% спред DEX + витрати провайдера", ru:"Без фиксированной комиссии · ~0,5–1% спред DEX + издержки провайдера", fr:"Pas de frais fixes · ~0,5–1 % de spread DEX + coûts prestataires", pt:"Sem taxa fixa · ~0,5–1% de spread DEX + custos do provedor", zh:"无固定费用 · 约 0.5–1% DEX 价差 + 服务商成本", ko:"고정 수수료 없음 · 약 0.5–1% DEX 스프레드 + 제공자 비용" };
D["Yes - equities & ETFs, 24/7"] = { es:"Sí: acciones y ETFs, 24/7", de:"Ja – Aktien & ETFs, rund um die Uhr", nl:"Ja - aandelen & ETF's, 24/7", uk:"Так — акції та ETF, 24/7", ru:"Да — акции и ETF, 24/7", fr:"Oui - actions et ETF, 24h/24", pt:"Sim - ações e ETFs, 24/7", zh:"支持——股票与 ETF，全天候", ko:"네 — 주식 & ETF, 24시간" };
D["Multi-device, any chain & token"] = { es:"Multidispositivo, cualquier cadena y token", de:"Mehrere Geräte, jede Chain & jeder Token", nl:"Meerdere apparaten, elke chain & token", uk:"Кілька пристроїв, будь-яка мережа і токен", ru:"Несколько устройств, любая сеть и токен", fr:"Multi-appareils, toute chaîne et token", pt:"Multidispositivo, qualquer rede e token", zh:"多设备，任意链与代币", ko:"멀티 디바이스, 모든 체인 & 토큰" };
D["Mastercard · 175+ countries · up to 2% cashback"] = { es:"Mastercard · más de 175 países · hasta 2% de cashback", de:"Mastercard · über 175 Länder · bis zu 2 % Cashback", nl:"Mastercard · 175+ landen · tot 2% cashback", uk:"Mastercard · понад 175 країн · до 2% кешбеку", ru:"Mastercard · более 175 стран · до 2% кешбэка", fr:"Mastercard · plus de 175 pays · jusqu'à 2 % de cashback", pt:"Mastercard · mais de 175 países · até 2% de cashback", zh:"Mastercard · 175+ 国家 · 最高 2% 返现", ko:"Mastercard · 175개국+ · 최대 2% 캐시백" };
D["Swiss IBAN & SEPA · CHF EUR USD RMB"] = { es:"IBAN suizo y SEPA · CHF EUR USD RMB", de:"Schweizer IBAN & SEPA · CHF EUR USD RMB", nl:"Zwitserse IBAN & SEPA · CHF EUR USD RMB", uk:"Швейцарський IBAN та SEPA · CHF EUR USD RMB", ru:"Швейцарский IBAN и SEPA · CHF EUR USD RMB", fr:"IBAN suisse et SEPA · CHF EUR USD RMB", pt:"IBAN suíço e SEPA · CHF EUR USD RMB", zh:"瑞士 IBAN 与 SEPA · 瑞郎 欧元 美元 人民币", ko:"스위스 IBAN & SEPA · CHF EUR USD RMB" };
D["Stablecoins, pools, $TITN staking"] = { es:"Stablecoins, pools y staking de $TITN", de:"Stablecoins, Pools, $TITN-Staking", nl:"Stablecoins, pools, $TITN-staking", uk:"Стейблкоїни, пули, стейкінг $TITN", ru:"Стейблкоины, пулы, стейкинг $TITN", fr:"Stablecoins, pools, staking $TITN", pt:"Stablecoins, pools, staking de $TITN", zh:"稳定币、流动性池、$TITN 质押", ko:"스테이블코인, 풀, $TITN 스테이킹" };
D["ETH & SOL staking"] = { es:"Staking de ETH y SOL", de:"ETH- & SOL-Staking", nl:"ETH & SOL staking", uk:"Стейкінг ETH та SOL", ru:"Стейкинг ETH и SOL", fr:"Staking ETH et SOL", pt:"Staking de ETH e SOL", zh:"ETH 与 SOL 质押", ko:"ETH & SOL 스테이킹" };
D["Staking on 25+ assets"] = { es:"Staking en más de 25 activos", de:"Staking für über 25 Assets", nl:"Staking op 25+ assets", uk:"Стейкінг понад 25 активів", ru:"Стейкинг более 25 активов", fr:"Staking sur plus de 25 actifs", pt:"Staking em mais de 25 ativos", zh:"支持 25+ 资产质押", ko:"25개+ 자산 스테이킹" };
D["Yield"] = { es:"Rendimiento", de:"Rendite", nl:"Rendement", uk:"Дохідність", ru:"Доходность", fr:"Rendement", pt:"Rendimento", zh:"收益", ko:"수익" };
D["Platforms"] = { es:"Plataformas", de:"Plattformen", nl:"Platforms", uk:"Платформи", ru:"Платформы", fr:"Plateformes", pt:"Plataformas", zh:"平台", ko:"플랫폼" };
D["RWA access - limited by region"] = { es:"Acceso a RWA, limitado por región", de:"RWA-Zugang – regional begrenzt", nl:"RWA-toegang - regionaal beperkt", uk:"Доступ до RWA — обмежений за регіоном", ru:"Доступ к RWA — ограничен по регионам", fr:"Accès RWA - limité par région", pt:"Acesso a RWA - limitado por região", zh:"RWA 访问——受地区限制", ko:"RWA 접근 — 지역 제한" };
D["Across chains & into the real world"] = { es:"Entre cadenas y hacia el mundo real", de:"Über Chains hinweg & in die echte Welt", nl:"Over chains heen & de echte wereld in", uk:"Через мережі — у реальний світ", ru:"Через сети — в реальный мир", fr:"À travers les chaînes et dans le monde réel", pt:"Entre redes e no mundo real", zh:"跨越链上，走进现实", ko:"체인을 넘어 현실 세계로" };
D["Deep Ethereum & dApp ecosystem"] = { es:"Profundo ecosistema de Ethereum y dApps", de:"Tiefes Ethereum- & dApp-Ökosystem", nl:"Diep Ethereum- & dApp-ecosysteem", uk:"Глибока екосистема Ethereum та dApp", ru:"Глубокая экосистема Ethereum и dApp", fr:"Écosystème Ethereum et dApps très riche", pt:"Ecossistema profundo de Ethereum e dApps", zh:"深厚的以太坊与 dApp 生态", ko:"깊은 이더리움 & dApp 생태계" };
D["Depth, security & real-world spend"] = { es:"Profundidad, seguridad y gasto en el mundo real", de:"Tiefe, Sicherheit & Ausgaben in der echten Welt", nl:"Diepte, veiligheid & uitgaven in de echte wereld", uk:"Глибина, безпека та витрати в реальному світі", ru:"Глубина, безопасность и траты в реальном мире", fr:"Profondeur, sécurité et dépenses réelles", pt:"Profundidade, segurança e gastos no mundo real", zh:"深度、安全与现实消费", ko:"깊이, 보안, 실생활 결제" };
D["Sheer breadth & reach"] = { es:"Pura amplitud y alcance", de:"Schiere Breite & Reichweite", nl:"Pure breedte & bereik", uk:"Неперевершена широта й охоплення", ru:"Непревзойдённая широта и охват", fr:"Une ampleur et une portée immenses", pt:"Pura amplitude e alcance", zh:"广度与覆盖面", ko:"압도적 폭과 도달 범위" };
D["Beyond one chain."] = { es:"Más allá de una cadena.", de:"Mehr als eine Chain.", nl:"Voorbij één chain.", uk:"Більше, ніж одна мережа.", ru:"Больше, чем одна сеть.", fr:"Au-delà d'une seule chaîne.", pt:"Além de uma única rede.", zh:"不止一条链。", ko:"하나의 체인을 넘어." };
D["Depth over breadth."] = { es:"Profundidad sobre amplitud.", de:"Tiefe statt Breite.", nl:"Diepte boven breedte.", uk:"Глибина понад широту.", ru:"Глубина важнее широты.", fr:"La profondeur plutôt que l'ampleur.", pt:"Profundidade acima de amplitude.", zh:"以深度胜广度。", ko:"폭보다 깊이." };
D["All comparisons"] = { es:"Todas las comparaciones", de:"Alle Vergleiche", nl:"Alle vergelijkingen", uk:"Усі порівняння", ru:"Все сравнения", fr:"Toutes les comparaisons", pt:"Todas as comparações", zh:"全部对比", ko:"모든 비교" };

})(window.__I18N__ = window.__I18N__ || {});
